apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
data:
  NODE_ENV: "production"
  KAFKA_BROKERS: "kafka-service:9092"
  ELASTICSEARCH_HOSTS: "http://elasticsearch-service:9200"
