-- Custom migration: sample seed data

-- 0001_sample_data: Seed users and login activities
-- Generated by scripts/sample-data/generate-sql-migrations.ts

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-001', 'pahakadmin@polydom.io', '$2a$10$rCo9V8PfvoyCwG8m1CAXzu.6MEB1oPtdvtZTz45IMuafg1AeC7DlS', 'Pahak', 'Admin', '+358401000001', 'ADMIN',
  '{"city":"Helsinki","country":"Finland","latitude":60.1699,"longitude":24.9384}',
  '{"musicalGenres":[],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":50}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-002', 'admin@example.com', '$2a$10$ckLvDOaqkcNlDEV4Njn4hOLuDq5Ifw1tEIwayXrE8SBSyKQWeYklS', 'Admin', 'User', '+358401000002', 'ADMIN',
  '{"city":"Helsinki","country":"Finland","latitude":60.1699,"longitude":24.9384}',
  '{"musicalGenres":[],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":50}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-003', 'ops@polydom.io', '$2a$10$Gz57XZiFXMX7uMFgqkAQFuD/64tFzE9Cxl27dAi8H3k2m87dEXOqC', 'Ops', 'Manager', '+358401000003', 'ADMIN',
  '{"city":"Espoo","country":"Finland","latitude":60.2055,"longitude":24.6559}',
  '{"musicalGenres":[],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":50}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-004', 'vendor@example.com', '$2a$10$tfxCQKwdrn36g6fUmx5xk.NQd5LV2xPsIkhP/UolEqZ88lKEI0CRq', 'Venue', 'Owner', '+358402000001', 'VENDOR',
  '{"city":"Helsinki","country":"Finland","latitude":60.1699,"longitude":24.9384}',
  '{"musicalGenres":["jazz","classical"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":30}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-005', 'harmony@polydom.io', '$2a$10$mjg.M7NaJ2Yz7qizOT3.K.km6rlKoRlsfOUGfzvQzpKBGOH6pnowm', 'Mika', 'Virtanen', '+358402000002', 'VENDOR',
  '{"city":"Helsinki","country":"Finland","latitude":60.1733,"longitude":24.941}',
  '{"musicalGenres":["rock","pop","electronic"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":25}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-006', 'gallery@polydom.io', '$2a$10$VkYLNTb0LDhqnCQ9gklfh.5951sCOS7uqDCNNLIa3W1TEWdaaEGLS', 'Sofia', 'Korhonen', '+358402000003', 'VENDOR',
  '{"city":"Espoo","country":"Finland","latitude":60.2055,"longitude":24.6559}',
  '{"musicalGenres":[],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":40}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-007', 'sports@polydom.io', '$2a$10$PjGi6cv.898WBy6QiSN43OcjUIIPHUGJq4Az0Yj2PStW0/8pjJ9R.', 'Jani', 'Mäkinen', '+358402000004', 'VENDOR',
  '{"city":"Vantaa","country":"Finland","latitude":60.2934,"longitude":25.0377}',
  '{"musicalGenres":[],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":35}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-008', 'activities@polydom.io', '$2a$10$7RnXPj9XjF/ygn7Oy3tzxOl1boPzs45AysD0EAW30PupFoShqZp06', 'Emma', 'Nieminen', '+358402000005', 'VENDOR',
  '{"city":"Helsinki","country":"Finland","latitude":60.1666,"longitude":24.9332}',
  '{"musicalGenres":[],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":20}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-009', 'user@example.com', '$2a$10$zgFFaCs18wlCGPI0Y7ShxO90gWgXoLfnmDnftLC/cxosEqUqBf0Xq', 'Music', 'Lover', '+358403000001', 'USER',
  '{"city":"Helsinki","country":"Finland","latitude":60.1699,"longitude":24.9384}',
  '{"musicalGenres":["jazz","blues","soul"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":30}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-010', 'anna@polydom.io', '$2a$10$5hLcduPCNhFvqg8tknCqbued7OvE6He3NymPr2L8X/C7rQxHHA3da', 'Anna', 'Järvinen', '+358403000002', 'USER',
  '{"city":"Helsinki","country":"Finland","latitude":60.172,"longitude":24.945}',
  '{"musicalGenres":["rock","metal","punk"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":50}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-011', 'mikko@polydom.io', '$2a$10$GrScJ8Lu5qq1PwzKSBp2se1wSYRN4btxZL8yKQvY.5HXYeK/kM9Vu', 'Mikko', 'Lahtinen', '+358403000003', 'USER',
  '{"city":"Espoo","country":"Finland","latitude":60.2055,"longitude":24.6559}',
  '{"musicalGenres":[],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":25}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-012', 'liisa@polydom.io', '$2a$10$XYW8Gm9Ran5x73ACMbmRYOsuH3gPfRzsa0P1kMqDn1AWQgE8GoXiy', 'Liisa', 'Hämäläinen', '+358403000004', 'USER',
  '{"city":"Vantaa","country":"Finland","latitude":60.2934,"longitude":25.0377}',
  '{"musicalGenres":["pop","hip-hop"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":35}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-013', 'juha@polydom.io', '$2a$10$a8acTyQdOmaUEkrhGiFaZeh3VxZatJxRY5J.qVfHhyNDLpu8XuCe6', 'Juha', 'Salonen', '+358403000005', 'USER',
  '{"city":"Helsinki","country":"Finland","latitude":60.167,"longitude":24.935}',
  '{"musicalGenres":["ambient","classical"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":15}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-014', 'pekka@polydom.io', '$2a$10$RKArcwkAw8BFvr7UVylc3urLcOP2VVjA8hx8H0e4KF1WxTi4R5A.C', 'Pekka', 'Heikkinen', '+358403000006', 'USER',
  '{"city":"Tampere","country":"Finland","latitude":61.4978,"longitude":23.761}',
  '{"musicalGenres":["electronic","techno","house"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":40}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-015', 'elina@polydom.io', '$2a$10$iwh2VqD8UZ2rAiVLSFpZUuPLn07FtcvuS5N1bQJUAjY6vsUdg1Ody', 'Elina', 'Koskinen', '+358403000007', 'USER',
  '{"city":"Turku","country":"Finland","latitude":60.4518,"longitude":22.2666}',
  '{"musicalGenres":["classical","opera"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":30}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-016', 'tommi@polydom.io', '$2a$10$L7Id0kAhrIvBUpkZCp5p5eod3qt1WSmv2NyFT3Ct6w1/gA6YMAh5i', 'Tommi', 'Lehtonen', '+358403000008', 'USER',
  '{"city":"Helsinki","country":"Finland","latitude":60.18,"longitude":24.95}',
  '{"musicalGenres":["rock","pop"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":20}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-017', 'sanna@polydom.io', '$2a$10$vzoeJzLz1o9nUHuMofaAn..VHatHU0lATAF8OUSlOgdp9HiyXxOzq', 'Sanna', 'Rantanen', '+358403000009', 'USER',
  '{"city":"Espoo","country":"Finland","latitude":60.21,"longitude":24.66}',
  '{"musicalGenres":["folk","indie"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":25}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-018', 'ville@polydom.io', '$2a$10$oU2i96h0WB9y4oR3POuLX.vqP2HHTj7480HZGePu1yqSFQNO6OXA6', 'Ville', 'Aaltonen', '+358403000010', 'USER',
  '{"city":"Helsinki","country":"Finland","latitude":60.163,"longitude":24.928}',
  '{"musicalGenres":["jazz","bossa nova"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":20}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-019', 'kati@polydom.io', '$2a$10$CX66Gu6Gh/XRCXbtxspAr.6ZkHVfiP7ovdZHoR4DfkQ2MsFCej4Xe', 'Kati', 'Peltola', '+358403000011', 'USER',
  '{"city":"Oulu","country":"Finland","latitude":65.0121,"longitude":25.4651}',
  '{"musicalGenres":["indie","alternative","folk"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":50}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-020', 'markus@polydom.io', '$2a$10$ylWXf0yqpVAGLIkTk.jmVeIEpKApJCvH1aPZjQY6rJmCLDsi0HITW', 'Markus', 'Saarinen', '+358403000012', 'USER',
  '{"city":"Helsinki","country":"Finland","latitude":60.171,"longitude":24.942}',
  '{"musicalGenres":["hip-hop","rap"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":15}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-021', 'jenni@polydom.io', '$2a$10$auZP9G5N.RhlmRdTUeDgqeVspgUfL3LzlfOUGpLTqfmtCo325/jMK', 'Jenni', 'Tuominen', '+358403000013', 'USER',
  '{"city":"Lahti","country":"Finland","latitude":60.9827,"longitude":25.6612}',
  '{"musicalGenres":["classical","jazz"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":40}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-022', 'olli@polydom.io', '$2a$10$UhlPVaqBHE7FXk2uSxRkM.g2o7c6U/FhOtD5UJf6c8GeME9uxIL3S', 'Olli', 'Mäkelä', '+358403000014', 'USER',
  '{"city":"Helsinki","country":"Finland","latitude":60.175,"longitude":24.937}',
  '{"musicalGenres":["rock","electronic"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":20}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-023', 'riikka@polydom.io', '$2a$10$9YiV1b4zLxtOstLDjQ5Llutrjp7Cw6d/Y8uIZql0ZjgjnFd.z.eQ6', 'Riikka', 'Kivi', '+358403000015', 'USER',
  '{"city":"Jyväskylä","country":"Finland","latitude":62.2426,"longitude":25.7473}',
  '{"musicalGenres":["pop","rock","electronic"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":100}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-024', 'antti@polydom.io', '$2a$10$f6pKyQOY1PiDJ31JvJ.SyuSMOkjPkwX9ghFNiblqQxx4cCofG7wkG', 'Antti', 'Kallio', '+358403000016', 'USER',
  '{"city":"Helsinki","country":"Finland","latitude":60.168,"longitude":24.932}',
  '{"musicalGenres":["ambient","experimental"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":25}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at)
VALUES (
  'user-025', 'minna@polydom.io', '$2a$10$yctAfxf3jG7l1ikqeigHIermjVLGht8fUE5e3OhAbWbX64s1AdzPe', 'Minna', 'Laine', '+358403000017', 'USER',
  '{"city":"Kuopio","country":"Finland","latitude":62.8924,"longitude":27.677}',
  '{"musicalGenres":["jazz","world music"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":60}',
  NOW(), NOW()
) ON CONFLICT (email) DO NOTHING;

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-001', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-001' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-002', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-002' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-003', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-003' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-004', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-004' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-005', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-005' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-006', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-006' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-007', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-007' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-008', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-008' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-009', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-009' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-010', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-010' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-011', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-011' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-012', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-012' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-013', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-013' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-014', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-014' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-015', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-015' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-016', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-016' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-017', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-017' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-018', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-018' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-019', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-019' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-020', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-020' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-021', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-021' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-022', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-022' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-023', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-023' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-024', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-024' AND event_type = 'LOGIN');

INSERT INTO user_activities (user_id, event_type, metadata, timestamp, ip_address, user_agent)
SELECT 'user-025', 'LOGIN', '{"source":"seed_script","ip":"127.0.0.1"}', NOW(), '127.0.0.1', 'SeedScript/1.0'
WHERE NOT EXISTS (SELECT 1 FROM user_activities WHERE user_id = 'user-025' AND event_type = 'LOGIN');
