-- Custom migration: sample seed data

-- 0001_sample_data: Seed events
-- Generated by scripts/sample-data/generate-sql-migrations.ts

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-001', 'vendor-001', 'venue-001', 'Jazz Night Live', 'An evening of smooth jazz featuring the Helsinki Jazz Quartet and special guests. Enjoy classic standards and original compositions in our main hall.',
  'MUSIC', 'Jazz', '2026-06-15T19:00:00Z', '2026-06-15T23:00:00Z',
  '{"venueName":"Jazz Night Live","address":"Helsinki, Finland","city":"Helsinki","latitude":60.1699,"longitude":24.9384}', '{"general":25,"vip":50,"currency":"EUR"}', 'CONTRACT', 500, 245,
  'PUBLISHED', '{jazz,live music,weekend}', 18, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-002', 'vendor-001', 'venue-002', 'Acoustic Fridays: Singer-Songwriter Night', 'Intimate acoustic performances by up-and-coming Finnish singer-songwriters. Every Friday in the Acoustic Lounge.',
  'MUSIC', 'Acoustic', '2026-06-20T20:00:00Z', '2026-06-20T23:00:00Z',
  '{"venueName":"Acoustic Fridays: Singer-Songwriter Night","address":"Helsinki, Finland","city":"Helsinki","latitude":60.1705,"longitude":24.939}', '{"general":15,"student":10,"currency":"EUR"}', 'CONTRACT', 120, 78,
  'PUBLISHED', '{acoustic,folk,friday,local artists}', NULL, true, 'WEEKLY', NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-003', 'vendor-002', 'venue-003', 'Electronic Music Production Workshop', 'Learn electronic music production techniques from professional producers. Hands-on session with Ableton Live, hardware synths, and mixing techniques.',
  'MUSIC', 'Music Production', '2026-06-25T14:00:00Z', '2026-06-25T18:00:00Z',
  '{"venueName":"Electronic Music Production Workshop","address":"Helsinki, Finland","city":"Helsinki","latitude":60.1733,"longitude":24.941}', '{"general":45,"student":30,"currency":"EUR"}', 'CONTRACT', 30, 22,
  'PUBLISHED', '{electronic,production,workshop,ableton}', 16, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-004', 'vendor-002', 'venue-004', 'Summer Rooftop Sessions: Indie Bands', 'Enjoy the Helsinki summer sunset with live indie bands on our rooftop. Drinks, music, and great vibes.',
  'MUSIC', 'Indie', '2026-07-05T18:00:00Z', '2026-07-05T22:00:00Z',
  '{"venueName":"Summer Rooftop Sessions: Indie Bands","address":"Helsinki, Finland","city":"Helsinki","latitude":60.173,"longitude":24.9415}', '{"general":20,"student":12,"currency":"EUR"}', 'CONTRACT', 150, 110,
  'PUBLISHED', '{rooftop,indie,summer,bands}', 18, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-005', 'vendor-001', 'venue-001', 'Classical Night: Sibelius & Beyond', 'The Helsinki Philharmonic performs Sibelius symphonies and modern Finnish classical works.',
  'MUSIC', 'Classical', '2026-04-10T19:00:00Z', '2026-04-10T22:00:00Z',
  '{"venueName":"Classical Night: Sibelius & Beyond","address":"Helsinki, Finland","city":"Helsinki","latitude":60.1699,"longitude":24.9384}', '{"general":35,"vip":70,"student":15,"currency":"EUR"}', 'CONTRACT', 500, 480,
  'COMPLETED', '{classical,sibelius,orchestra}', NULL, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-006', 'vendor-001', 'venue-002', 'Blues & Bourbon Night', 'Deep south blues paired with curated bourbon tasting. Featuring the Dirty Fingers Blues Band.',
  'MUSIC', 'Blues', '2026-04-25T20:00:00Z', '2026-04-26T01:00:00Z',
  '{"venueName":"Blues & Bourbon Night","address":"Helsinki, Finland","city":"Helsinki","latitude":60.1705,"longitude":24.939}', '{"general":30,"vip":55,"currency":"EUR"}', 'CONTRACT', 120, 120,
  'COMPLETED', '{blues,bourbon,tasting}', 21, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-007', 'vendor-002', 'venue-003', 'Rock Guitar Workshop', 'Learn rock guitar techniques from professional musicians. Covers lead guitar, rhythm, tone shaping, and soloing. All skill levels welcome.',
  'MUSIC', 'Music Education', '2026-04-18T10:00:00Z', '2026-04-18T16:00:00Z',
  '{"venueName":"Rock Guitar Workshop","address":"Helsinki, Finland","city":"Helsinki","latitude":60.1733,"longitude":24.941}', '{"general":40,"student":25,"currency":"EUR"}', 'CONTRACT', 30, 28,
  'COMPLETED', '{workshop,guitar,rock,education}', 14, true, 'MONTHLY', NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-008', 'vendor-002', 'venue-004', 'Techno Underground', 'Late-night techno party featuring Berlin-based DJs and immersive light installations.',
  'MUSIC', 'Electronic', '2026-05-03T22:00:00Z', '2026-05-04T04:00:00Z',
  '{"venueName":"Techno Underground","address":"Helsinki, Finland","city":"Helsinki","latitude":60.173,"longitude":24.9415}', '{"general":22,"currency":"EUR"}', 'CONTRACT', 150, 145,
  'COMPLETED', '{techno,electronic,late night,DJ}', 20, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-009', 'vendor-001', 'venue-001', 'Summer Music Festival 2026', 'Two-day outdoor-to-indoor festival featuring 20+ bands across 2 stages. Food trucks, art installations, and camping options.',
  'MUSIC', 'Festival', '2026-07-25T14:00:00Z', '2026-07-26T23:00:00Z',
  '{"venueName":"Summer Music Festival 2026","address":"Helsinki, Finland","city":"Helsinki","latitude":60.1699,"longitude":24.9384}', '{"general":85,"vip":150,"student":55,"currency":"EUR"}', 'CONTRACT', 500, 320,
  'PUBLISHED', '{festival,summer,multi-day,food trucks}', 18, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-010', 'vendor-001', 'venue-001', 'New Year Gala Concert', 'Elegant New Year celebration with waltz orchestra, champagne, and fireworks viewing from our balcony.',
  'MUSIC', 'Classical', '2026-12-31T20:00:00Z', '2027-01-01T01:00:00Z',
  '{"venueName":"New Year Gala Concert","address":"Helsinki, Finland","city":"Helsinki","latitude":60.1699,"longitude":24.9384}', '{"general":120,"vip":200,"currency":"EUR"}', 'CONTRACT', 500, 150,
  'PUBLISHED', '{new year,gala,classical,champagne}', 18, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-011', 'vendor-002', 'venue-003', 'Vinyl Listening Party', 'Bring your favorite records and discover new ones. Analog listening on high-end equipment with fellow audiophiles.',
  'MUSIC', 'Listening Party', '2026-05-20T19:00:00Z', '2026-05-20T22:00:00Z',
  '{"venueName":"Vinyl Listening Party","address":"Helsinki, Finland","city":"Helsinki","latitude":60.1733,"longitude":24.941}', '{"general":0,"currency":"EUR"}', 'FREE', 80, 65,
  'COMPLETED', '{vinyl,listening party,audiophile,free}', NULL, true, 'MONTHLY', NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-012', 'vendor-002', 'venue-003', 'Songwriting Masterclass', 'Intensive songwriting workshop with Grammy-nominated songwriter. Limited to 20 participants for focused mentoring.',
  'MUSIC', 'Masterclass', '2026-07-10T10:00:00Z', '2026-07-10T17:00:00Z',
  '{"venueName":"Songwriting Masterclass","address":"Helsinki, Finland","city":"Helsinki","latitude":60.1733,"longitude":24.941}', '{"general":150,"student":100,"currency":"EUR"}', 'CONTRACT', 20, 8,
  'PUBLISHED', '{masterclass,songwriting,mentoring}', 16, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-013', 'vendor-003', 'venue-005', 'Nordic Contemporary Art Exhibition', 'Showcasing the best of Nordic contemporary art: paintings, installations, and mixed media from 15 emerging artists.',
  'ART', 'Exhibition', '2026-06-01T10:00:00Z', '2026-06-30T18:00:00Z',
  '{"venueName":"Nordic Contemporary Art Exhibition","address":"Espoo, Finland","city":"Espoo","latitude":60.2055,"longitude":24.6559}', '{"general":12,"student":6,"currency":"EUR"}', 'CONTRACT', 200, 85,
  'PUBLISHED', '{contemporary,nordic,exhibition,painting}', NULL, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-014', 'vendor-003', 'venue-006', 'Watercolor Workshop for Beginners', 'Learn watercolor painting basics in a relaxed, supportive environment. All materials provided.',
  'ART', 'Workshop', '2026-06-14T13:00:00Z', '2026-06-14T16:00:00Z',
  '{"venueName":"Watercolor Workshop for Beginners","address":"Espoo, Finland","city":"Espoo","latitude":60.206,"longitude":24.6565}', '{"general":35,"student":25,"currency":"EUR"}', 'CONTRACT', 40, 32,
  'PUBLISHED', '{watercolor,beginner,workshop,painting}', 12, true, 'WEEKLY', NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-015', 'vendor-004', 'venue-007', 'Sculpture in the Park: Summer Exhibition', 'Annual outdoor sculpture exhibition set in our beautiful sculpture park. Featuring large-scale works by Finnish sculptors.',
  'ART', 'Exhibition', '2026-06-15T10:00:00Z', '2026-08-31T20:00:00Z',
  '{"venueName":"Sculpture in the Park: Summer Exhibition","address":"Espoo, Finland","city":"Espoo","latitude":60.21,"longitude":24.65}', '{"general":0,"currency":"EUR"}', 'FREE', 500, 0,
  'PUBLISHED', '{sculpture,outdoor,summer,free}', NULL, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-016', 'vendor-004', 'venue-008', 'Stone Carving Intensive', 'Three-day intensive stone carving workshop. Learn traditional and modern techniques from master sculptor Eero Mäntynen.',
  'ART', 'Workshop', '2026-07-15T09:00:00Z', '2026-07-17T17:00:00Z',
  '{"venueName":"Stone Carving Intensive","address":"Espoo, Finland","city":"Espoo","latitude":60.2095,"longitude":24.6505}', '{"general":280,"currency":"EUR"}', 'CONTRACT', 12, 6,
  'PUBLISHED', '{stone carving,sculpture,intensive,masterclass}', 18, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-017', 'vendor-003', 'venue-005', 'Photography Exhibition: Helsinki Streets', 'Street photography capturing the essence of Helsinki neighborhoods through the seasons.',
  'ART', 'Photography', '2026-04-05T11:00:00Z', '2026-05-15T18:00:00Z',
  '{"venueName":"Photography Exhibition: Helsinki Streets","address":"Espoo, Finland","city":"Espoo","latitude":60.2055,"longitude":24.6559}', '{"general":8,"student":4,"currency":"EUR"}', 'CONTRACT', 200, 190,
  'COMPLETED', '{photography,helsinki,street,exhibition}', NULL, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-018', 'vendor-003', 'venue-006', 'Pottery & Wine Evening', 'Relaxed evening of pottery making with wine and cheese. No experience needed — create your own ceramic piece.',
  'ART', 'Social', '2026-05-08T18:00:00Z', '2026-05-08T21:00:00Z',
  '{"venueName":"Pottery & Wine Evening","address":"Espoo, Finland","city":"Espoo","latitude":60.206,"longitude":24.6565}', '{"general":45,"currency":"EUR"}', 'CONTRACT', 30, 30,
  'COMPLETED', '{pottery,wine,social,beginner}', 18, true, 'MONTHLY', NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-019', 'vendor-004', 'venue-008', 'Metal Art Welding Workshop', 'Introduction to metal art and welding. Create your own metal sculpture under expert supervision. Safety gear provided.',
  'ART', 'Workshop', '2026-07-22T10:00:00Z', '2026-07-22T16:00:00Z',
  '{"venueName":"Metal Art Welding Workshop","address":"Espoo, Finland","city":"Espoo","latitude":60.2095,"longitude":24.6505}', '{"general":95,"student":70,"currency":"EUR"}', 'CONTRACT', 15, 5,
  'PUBLISHED', '{welding,metal art,workshop,sculpture}', 18, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-020', 'vendor-003', 'venue-005', 'Art After Dark: Neon & Light Installations', 'Evening exhibition of immersive light art and neon installations. Interactive pieces, ambient music, and cocktails.',
  'ART', 'Exhibition', '2026-05-30T20:00:00Z', '2026-05-31T01:00:00Z',
  '{"venueName":"Art After Dark: Neon & Light Installations","address":"Espoo, Finland","city":"Espoo","latitude":60.2055,"longitude":24.6559}', '{"general":18,"vip":35,"currency":"EUR"}', 'CONTRACT', 200, 200,
  'COMPLETED', '{light art,neon,night,immersive}', 18, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-021', 'vendor-005', 'venue-009', '3v3 Basketball Tournament', 'Fast-paced 3-on-3 street basketball tournament. Team registration, prizes for winners, and after-party.',
  'SPORTS', 'Basketball', '2026-07-12T10:00:00Z', '2026-07-12T18:00:00Z',
  '{"venueName":"3v3 Basketball Tournament","address":"Vantaa, Finland","city":"Vantaa","latitude":60.2934,"longitude":25.0377}', '{"general":25,"currency":"EUR"}', 'CONTRACT', 800, 320,
  'PUBLISHED', '{basketball,tournament,3v3,team}', 14, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-022', 'vendor-005', 'venue-010', 'Beginner Bouldering Clinic', 'Introduction to bouldering: technique, safety, and route reading. No experience required. Includes day pass.',
  'SPORTS', 'Climbing', '2026-06-28T14:00:00Z', '2026-06-28T17:00:00Z',
  '{"venueName":"Beginner Bouldering Clinic","address":"Vantaa, Finland","city":"Vantaa","latitude":60.294,"longitude":25.038}', '{"general":30,"student":20,"currency":"EUR"}', 'CONTRACT', 30, 18,
  'PUBLISHED', '{bouldering,climbing,beginner,clinic}', 10, true, 'WEEKLY', NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-023', 'vendor-006', 'venue-011', 'Adult Tennis League — Spring 2026', 'Competitive adult tennis league. 8-week season with playoffs. Doubles and singles divisions.',
  'SPORTS', 'Tennis', '2026-04-01T18:00:00Z', '2026-05-31T21:00:00Z',
  '{"venueName":"Adult Tennis League — Spring 2026","address":"Helsinki, Finland","city":"Helsinki","latitude":60.19,"longitude":24.96}', '{"general":120,"student":80,"currency":"EUR"}', 'CONTRACT', 50, 50,
  'COMPLETED', '{tennis,league,competitive,season}', 18, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-024', 'vendor-006', 'venue-012', 'Kids Summer Tennis Camp', 'Week-long tennis camp for kids ages 7-14. Coaching, games, swimming, and lunch included.',
  'SPORTS', 'Tennis', '2026-07-06T09:00:00Z', '2026-07-10T15:00:00Z',
  '{"venueName":"Kids Summer Tennis Camp","address":"Helsinki, Finland","city":"Helsinki","latitude":60.1905,"longitude":24.961}', '{"general":200,"currency":"EUR"}', 'CONTRACT', 40, 25,
  'PUBLISHED', '{tennis,kids,camp,summer}', NULL, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-025', 'vendor-005', 'venue-009', 'Volleyball Open Play', 'Casual volleyball for all skill levels. Rotating teams, friendly atmosphere. Drop in any time.',
  'SPORTS', 'Volleyball', '2026-06-17T19:00:00Z', '2026-06-17T22:00:00Z',
  '{"venueName":"Volleyball Open Play","address":"Vantaa, Finland","city":"Vantaa","latitude":60.2934,"longitude":25.0377}', '{"general":10,"currency":"EUR"}', 'PER_HOUR', 100, 45,
  'PUBLISHED', '{volleyball,casual,open play,drop-in}', NULL, true, 'WEEKLY', NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-026', 'vendor-005', 'venue-009', 'Corporate Sports Day', 'Team building through sports: relay races, tug-of-war, dodgeball, and more. Catering and medals included.',
  'SPORTS', 'Team Building', '2026-04-22T09:00:00Z', '2026-04-22T17:00:00Z',
  '{"venueName":"Corporate Sports Day","address":"Vantaa, Finland","city":"Vantaa","latitude":60.2934,"longitude":25.0377}', '{"general":0,"currency":"EUR"}', 'CONTRACT', 200, 180,
  'COMPLETED', '{corporate,team building,sports day}', 18, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-027', 'vendor-006', 'venue-011', 'Tennis Doubles Social', 'Social doubles tennis with rotating partners. Pizza and drinks afterward. Great way to meet other players.',
  'SPORTS', 'Tennis', '2026-06-11T18:00:00Z', '2026-06-11T21:00:00Z',
  '{"venueName":"Tennis Doubles Social","address":"Helsinki, Finland","city":"Helsinki","latitude":60.19,"longitude":24.96}', '{"general":20,"currency":"EUR"}', 'CONTRACT', 32, 20,
  'PUBLISHED', '{tennis,doubles,social,pizza}', 16, true, 'MONTHLY', NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-028', 'vendor-005', 'venue-010', 'Advanced Lead Climbing Course', 'Intensive lead climbing course for experienced climbers. Covers advanced techniques, fall practice, and route setting.',
  'SPORTS', 'Climbing', '2026-07-19T10:00:00Z', '2026-07-19T17:00:00Z',
  '{"venueName":"Advanced Lead Climbing Course","address":"Vantaa, Finland","city":"Vantaa","latitude":60.294,"longitude":25.038}', '{"general":85,"currency":"EUR"}', 'CONTRACT', 12, 7,
  'PUBLISHED', '{climbing,lead,advanced,course}', 16, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-029', 'vendor-006', 'venue-011', 'Parent-Child Tennis Fun Day', 'Fun tennis activities for parents and children. Games, drills, and a mini-tournament. Rackets provided if needed.',
  'SPORTS', 'Tennis', '2026-05-17T10:00:00Z', '2026-05-17T14:00:00Z',
  '{"venueName":"Parent-Child Tennis Fun Day","address":"Helsinki, Finland","city":"Helsinki","latitude":60.19,"longitude":24.96}', '{"general":15,"currency":"EUR"}', 'CONTRACT', 40, 35,
  'COMPLETED', '{tennis,family,kids,fun}', NULL, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-030', 'vendor-005', 'venue-009', 'Summer Basketball Camp', 'Intensive basketball camp for teens. Professional coaching, skill development, scrimmages, and guest pro appearances.',
  'SPORTS', 'Basketball', '2026-07-27T09:00:00Z', '2026-07-31T16:00:00Z',
  '{"venueName":"Summer Basketball Camp","address":"Vantaa, Finland","city":"Vantaa","latitude":60.2934,"longitude":25.0377}', '{"general":180,"currency":"EUR"}', 'CONTRACT', 60, 28,
  'PUBLISHED', '{basketball,camp,teens,summer}', NULL, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-031', 'vendor-007', 'venue-013', 'Morning Yoga Flow', 'Start your day with an energizing vinyasa flow. Suitable for all levels. Mats provided.',
  'ACTIVITIES', 'Yoga', '2026-06-16T07:00:00Z', '2026-06-16T08:15:00Z',
  '{"venueName":"Morning Yoga Flow","address":"Helsinki, Finland","city":"Helsinki","latitude":60.1666,"longitude":24.9332}', '{"general":15,"student":10,"currency":"EUR"}', 'PER_HOUR', 40, 25,
  'PUBLISHED', '{yoga,morning,vinyasa,wellness}', NULL, true, 'DAILY', NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-032', 'vendor-007', 'venue-014', 'Guided Meditation & Sound Bath', 'Deep relaxation through guided meditation and crystal singing bowl sound bath in our peaceful garden.',
  'ACTIVITIES', 'Meditation', '2026-06-18T18:00:00Z', '2026-06-18T19:30:00Z',
  '{"venueName":"Guided Meditation & Sound Bath","address":"Helsinki, Finland","city":"Helsinki","latitude":60.167,"longitude":24.933}', '{"general":20,"currency":"EUR"}', 'CONTRACT', 30, 18,
  'PUBLISHED', '{meditation,sound bath,relaxation,garden}', NULL, true, 'WEEKLY', NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-033', 'vendor-008', 'venue-015', 'Finnish Cuisine Cooking Class', 'Learn to make traditional Finnish dishes: salmon soup, Karelian pies, and cinnamon buns. Dinner and wine included.',
  'ACTIVITIES', 'Cooking', '2026-06-22T17:00:00Z', '2026-06-22T21:00:00Z',
  '{"venueName":"Finnish Cuisine Cooking Class","address":"Helsinki, Finland","city":"Helsinki","latitude":60.17,"longitude":24.93}', '{"general":65,"currency":"EUR"}', 'CONTRACT', 24, 18,
  'PUBLISHED', '{cooking,finnish,cuisine,food}', 16, true, 'WEEKLY', NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-034', 'vendor-008', 'venue-016', 'Forest Foraging & Wild Food Walk', 'Guided foraging walk in Nuuksio National Park. Learn to identify edible mushrooms, berries, and herbs. Picnic lunch included.',
  'ACTIVITIES', 'Outdoor', '2026-07-05T09:00:00Z', '2026-07-05T14:00:00Z',
  '{"venueName":"Forest Foraging & Wild Food Walk","address":"Helsinki, Finland","city":"Helsinki","latitude":60.171,"longitude":24.929}', '{"general":40,"student":30,"currency":"EUR"}', 'CONTRACT', 20, 12,
  'PUBLISHED', '{foraging,forest,wild food,outdoor}', 12, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-035', 'vendor-007', 'venue-013', 'Prenatal Yoga Series', 'Gentle yoga for expecting mothers. Focus on breathing, stretching, and preparation for childbirth. 6-week series.',
  'ACTIVITIES', 'Yoga', '2026-04-08T10:00:00Z', '2026-05-13T11:30:00Z',
  '{"venueName":"Prenatal Yoga Series","address":"Helsinki, Finland","city":"Helsinki","latitude":60.1666,"longitude":24.9332}', '{"general":120,"currency":"EUR"}', 'CONTRACT', 20, 16,
  'COMPLETED', '{prenatal,yoga,pregnancy,wellness}', 18, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-036', 'vendor-008', 'venue-015', 'Sourdough Bread Baking Workshop', 'Master the art of sourdough: starter maintenance, kneading, shaping, and baking. Take home your own starter and fresh bread.',
  'ACTIVITIES', 'Baking', '2026-05-24T10:00:00Z', '2026-05-24T15:00:00Z',
  '{"venueName":"Sourdough Bread Baking Workshop","address":"Helsinki, Finland","city":"Helsinki","latitude":60.17,"longitude":24.93}', '{"general":55,"currency":"EUR"}', 'CONTRACT', 16, 16,
  'COMPLETED', '{sourdough,baking,bread,workshop}', 14, true, 'MONTHLY', NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-037', 'vendor-007', 'venue-014', 'Full Moon Yoga & Cacao Ceremony', 'Special full moon celebration: gentle yoga, cacao ceremony, intention setting, and fire pit gathering.',
  'ACTIVITIES', 'Ceremony', '2026-07-08T20:00:00Z', '2026-07-08T23:00:00Z',
  '{"venueName":"Full Moon Yoga & Cacao Ceremony","address":"Helsinki, Finland","city":"Helsinki","latitude":60.167,"longitude":24.933}', '{"general":35,"currency":"EUR"}', 'CONTRACT', 30, 22,
  'PUBLISHED', '{full moon,yoga,cacao,ceremony}', 16, false, NULL, NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-038', 'vendor-008', 'venue-016', 'Kayaking Adventure: Helsinki Archipelago', 'Guided sea kayaking trip through the Helsinki archipelago. Suitable for beginners. All equipment and lunch provided.',
  'ACTIVITIES', 'Adventure', '2026-07-15T09:00:00Z', '2026-07-15T17:00:00Z',
  '{"venueName":"Kayaking Adventure: Helsinki Archipelago","address":"Helsinki, Finland","city":"Helsinki","latitude":60.171,"longitude":24.929}', '{"general":75,"currency":"EUR"}', 'CONTRACT', 16, 10,
  'PUBLISHED', '{kayaking,archipelago,adventure,outdoor}', 14, true, 'WEEKLY', NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-039', 'vendor-008', 'venue-015', 'Wine Tasting: European Reds', 'Guided tasting of 8 premium European red wines paired with artisan cheeses. Led by certified sommelier.',
  'ACTIVITIES', 'Wine Tasting', '2026-05-29T19:00:00Z', '2026-05-29T22:00:00Z',
  '{"venueName":"Wine Tasting: European Reds","address":"Helsinki, Finland","city":"Helsinki","latitude":60.17,"longitude":24.93}', '{"general":55,"vip":80,"currency":"EUR"}', 'CONTRACT', 24, 24,
  'COMPLETED', '{wine,tasting,european,cheese}', 20, true, 'MONTHLY', NOW(), NOW()
);

INSERT INTO events (id, vendor_id, venue_id, title, description, category, sub_category, start_time, end_time, location, price, pricing_model, max_attendees, current_bookings, status, tags, age_restriction, is_recurring, recurring_rule, created_at, updated_at)
VALUES (
  'event-040', 'vendor-007', 'venue-013', 'Weekend Wellness Retreat', 'Full weekend of yoga, meditation, breathwork, and healthy meals. Reset your mind and body in our serene space.',
  'ACTIVITIES', 'Retreat', '2026-07-18T09:00:00Z', '2026-07-19T17:00:00Z',
  '{"venueName":"Weekend Wellness Retreat","address":"Helsinki, Finland","city":"Helsinki","latitude":60.1666,"longitude":24.9332}', '{"general":250,"currency":"EUR"}', 'CONTRACT', 24, 14,
  'PUBLISHED', '{retreat,wellness,weekend,yoga}', 16, false, NULL, NOW(), NOW()
);
