/**
 * Sample Data Constants — Single source of truth for all deterministic IDs.
 * Imported by all service seed files to ensure cross-service referential integrity.
 *
 * Geography: All data centered around Helsinki, Finland
 * Date range: 2026-04-01 to 2026-07-31
 */

// ======================== USERS ========================
export interface SampleUser {
  id: string;
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  role: 'USER' | 'VENDOR' | 'ADMIN';
  phone: string;
  city: string;
  lat: number;
  lng: number;
  interests: string[];
  genres: string[];
  searchRadius: number;
}

export const SAMPLE_USERS: SampleUser[] = [
  // --- Admins (3) ---
  { id: 'user-001', email: 'pahakadmin@polydom.io', password: 'Three1288', firstName: 'Pahak', lastName: 'Admin', role: 'ADMIN', phone: '+358401000001', city: 'Helsinki', lat: 60.1699, lng: 24.9384, interests: ['system', 'analytics'], genres: [], searchRadius: 50 },
  { id: 'user-002', email: 'admin@example.com', password: 'admin123', firstName: 'Admin', lastName: 'User', role: 'ADMIN', phone: '+358401000002', city: 'Helsinki', lat: 60.1699, lng: 24.9384, interests: ['platform management'], genres: [], searchRadius: 50 },
  { id: 'user-003', email: 'ops@polydom.io', password: 'ops123!', firstName: 'Ops', lastName: 'Manager', role: 'ADMIN', phone: '+358401000003', city: 'Espoo', lat: 60.2055, lng: 24.6559, interests: ['devops', 'monitoring'], genres: [], searchRadius: 50 },

  // --- Vendors (5) ---
  { id: 'user-004', email: 'vendor@example.com', password: 'vendor123', firstName: 'Venue', lastName: 'Owner', role: 'VENDOR', phone: '+358402000001', city: 'Helsinki', lat: 60.1699, lng: 24.9384, interests: ['venue management', 'event hosting'], genres: ['jazz', 'classical'], searchRadius: 30 },
  { id: 'user-005', email: 'harmony@polydom.io', password: 'vendor123', firstName: 'Mika', lastName: 'Virtanen', role: 'VENDOR', phone: '+358402000002', city: 'Helsinki', lat: 60.1733, lng: 24.9410, interests: ['music production', 'recording'], genres: ['rock', 'pop', 'electronic'], searchRadius: 25 },
  { id: 'user-006', email: 'gallery@polydom.io', password: 'vendor123', firstName: 'Sofia', lastName: 'Korhonen', role: 'VENDOR', phone: '+358402000003', city: 'Espoo', lat: 60.2055, lng: 24.6559, interests: ['contemporary art', 'sculpture'], genres: [], searchRadius: 40 },
  { id: 'user-007', email: 'sports@polydom.io', password: 'vendor123', firstName: 'Jani', lastName: 'Mäkinen', role: 'VENDOR', phone: '+358402000004', city: 'Vantaa', lat: 60.2934, lng: 25.0377, interests: ['sports', 'fitness'], genres: [], searchRadius: 35 },
  { id: 'user-008', email: 'activities@polydom.io', password: 'vendor123', firstName: 'Emma', lastName: 'Nieminen', role: 'VENDOR', phone: '+358402000005', city: 'Helsinki', lat: 60.1666, lng: 24.9332, interests: ['yoga', 'wellness', 'outdoor'], genres: [], searchRadius: 20 },

  // --- Regular Users (17) ---
  { id: 'user-009', email: 'user@example.com', password: 'user123', firstName: 'Music', lastName: 'Lover', role: 'USER', phone: '+358403000001', city: 'Helsinki', lat: 60.1699, lng: 24.9384, interests: ['live music', 'jazz', 'concerts'], genres: ['jazz', 'blues', 'soul'], searchRadius: 30 },
  { id: 'user-010', email: 'anna@polydom.io', password: 'user123', firstName: 'Anna', lastName: 'Järvinen', role: 'USER', phone: '+358403000002', city: 'Helsinki', lat: 60.1720, lng: 24.9450, interests: ['rock music', 'festivals', 'guitar'], genres: ['rock', 'metal', 'punk'], searchRadius: 50 },
  { id: 'user-011', email: 'mikko@polydom.io', password: 'user123', firstName: 'Mikko', lastName: 'Lahtinen', role: 'USER', phone: '+358403000003', city: 'Espoo', lat: 60.2055, lng: 24.6559, interests: ['art exhibitions', 'painting', 'photography'], genres: [], searchRadius: 25 },
  { id: 'user-012', email: 'liisa@polydom.io', password: 'user123', firstName: 'Liisa', lastName: 'Hämäläinen', role: 'USER', phone: '+358403000004', city: 'Vantaa', lat: 60.2934, lng: 25.0377, interests: ['sports', 'basketball', 'running'], genres: ['pop', 'hip-hop'], searchRadius: 35 },
  { id: 'user-013', email: 'juha@polydom.io', password: 'user123', firstName: 'Juha', lastName: 'Salonen', role: 'USER', phone: '+358403000005', city: 'Helsinki', lat: 60.1670, lng: 24.9350, interests: ['yoga', 'meditation', 'wellness'], genres: ['ambient', 'classical'], searchRadius: 15 },
  { id: 'user-014', email: 'pekka@polydom.io', password: 'user123', firstName: 'Pekka', lastName: 'Heikkinen', role: 'USER', phone: '+358403000006', city: 'Tampere', lat: 61.4978, lng: 23.7610, interests: ['electronic music', 'DJ sets', 'clubbing'], genres: ['electronic', 'techno', 'house'], searchRadius: 40 },
  { id: 'user-015', email: 'elina@polydom.io', password: 'user123', firstName: 'Elina', lastName: 'Koskinen', role: 'USER', phone: '+358403000007', city: 'Turku', lat: 60.4518, lng: 22.2666, interests: ['theatre', 'dance', 'performance'], genres: ['classical', 'opera'], searchRadius: 30 },
  { id: 'user-016', email: 'tommi@polydom.io', password: 'user123', firstName: 'Tommi', lastName: 'Lehtonen', role: 'USER', phone: '+358403000008', city: 'Helsinki', lat: 60.1800, lng: 24.9500, interests: ['football', 'sports events', 'outdoor'], genres: ['rock', 'pop'], searchRadius: 20 },
  { id: 'user-017', email: 'sanna@polydom.io', password: 'user123', firstName: 'Sanna', lastName: 'Rantanen', role: 'USER', phone: '+358403000009', city: 'Espoo', lat: 60.2100, lng: 24.6600, interests: ['crafts', 'workshops', 'DIY'], genres: ['folk', 'indie'], searchRadius: 25 },
  { id: 'user-018', email: 'ville@polydom.io', password: 'user123', firstName: 'Ville', lastName: 'Aaltonen', role: 'USER', phone: '+358403000010', city: 'Helsinki', lat: 60.1630, lng: 24.9280, interests: ['food festivals', 'cooking', 'wine tasting'], genres: ['jazz', 'bossa nova'], searchRadius: 20 },
  { id: 'user-019', email: 'kati@polydom.io', password: 'user123', firstName: 'Kati', lastName: 'Peltola', role: 'USER', phone: '+358403000011', city: 'Oulu', lat: 65.0121, lng: 25.4651, interests: ['indie music', 'vinyl collecting', 'concerts'], genres: ['indie', 'alternative', 'folk'], searchRadius: 50 },
  { id: 'user-020', email: 'markus@polydom.io', password: 'user123', firstName: 'Markus', lastName: 'Saarinen', role: 'USER', phone: '+358403000012', city: 'Helsinki', lat: 60.1710, lng: 24.9420, interests: ['basketball', 'gym', 'health'], genres: ['hip-hop', 'rap'], searchRadius: 15 },
  { id: 'user-021', email: 'jenni@polydom.io', password: 'user123', firstName: 'Jenni', lastName: 'Tuominen', role: 'USER', phone: '+358403000013', city: 'Lahti', lat: 60.9827, lng: 25.6612, interests: ['painting', 'art classes', 'ceramics'], genres: ['classical', 'jazz'], searchRadius: 40 },
  { id: 'user-022', email: 'olli@polydom.io', password: 'user123', firstName: 'Olli', lastName: 'Mäkelä', role: 'USER', phone: '+358403000014', city: 'Helsinki', lat: 60.1750, lng: 24.9370, interests: ['tennis', 'padel', 'squash'], genres: ['rock', 'electronic'], searchRadius: 20 },
  { id: 'user-023', email: 'riikka@polydom.io', password: 'user123', firstName: 'Riikka', lastName: 'Kivi', role: 'USER', phone: '+358403000015', city: 'Jyväskylä', lat: 62.2426, lng: 25.7473, interests: ['festivals', 'summer events', 'outdoor concerts'], genres: ['pop', 'rock', 'electronic'], searchRadius: 100 },
  { id: 'user-024', email: 'antti@polydom.io', password: 'user123', firstName: 'Antti', lastName: 'Kallio', role: 'USER', phone: '+358403000016', city: 'Helsinki', lat: 60.1680, lng: 24.9320, interests: ['photography', 'film', 'visual arts'], genres: ['ambient', 'experimental'], searchRadius: 25 },
  { id: 'user-025', email: 'minna@polydom.io', password: 'user123', firstName: 'Minna', lastName: 'Laine', role: 'USER', phone: '+358403000017', city: 'Kuopio', lat: 62.8924, lng: 27.6770, interests: ['wine', 'culinary', 'cultural events'], genres: ['jazz', 'world music'], searchRadius: 60 },
];

// ======================== VENDORS ========================
export interface SampleVendorData {
  id: string;
  userId: string;
  businessName: string;
  description: string;
  category: 'MUSIC' | 'ART' | 'SPORTS' | 'ACTIVITIES' | 'OTHER';
  subCategory: string;
  contactEmail: string;
  contactPhone: string;
  website: string;
  city: string;
  lat: number;
  lng: number;
  streetAddress: string;
  verificationStatus: string;
  rating: number;
  totalReviews: number;
}

export const SAMPLE_VENDORS: SampleVendorData[] = [
  // --- MUSIC (2) ---
  { id: 'vendor-001', userId: 'user-004', businessName: 'LA Music Hall', description: 'Premier music venue hosting top artists from Finland and beyond', category: 'MUSIC', subCategory: 'Live Music Venue', contactEmail: 'info@lamusichall.com', contactPhone: '+358402000001', website: 'https://lamusichall.fi', city: 'Helsinki', lat: 60.1699, lng: 24.9384, streetAddress: 'Mannerheimintie 13, 00100 Helsinki', verificationStatus: 'VERIFIED', rating: 4.8, totalReviews: 125 },
  { id: 'vendor-002', userId: 'user-005', businessName: 'Harmony Studios', description: 'Professional recording studio and intimate live performance space', category: 'MUSIC', subCategory: 'Recording Studio & Venue', contactEmail: 'info@harmonystudios.fi', contactPhone: '+358402000002', website: 'https://harmonystudios.fi', city: 'Helsinki', lat: 60.1733, lng: 24.9410, streetAddress: 'Fredrikinkatu 25, 00120 Helsinki', verificationStatus: 'VERIFIED', rating: 4.6, totalReviews: 89 },

  // --- ART (2) ---
  { id: 'vendor-003', userId: 'user-006', businessName: 'Canvas & Cork Gallery', description: 'Contemporary art gallery showcasing emerging Finnish and Nordic artists', category: 'ART', subCategory: 'Art Gallery', contactEmail: 'info@canvasandcork.fi', contactPhone: '+358402000003', website: 'https://canvasandcork.fi', city: 'Espoo', lat: 60.2055, lng: 24.6559, streetAddress: 'Tapiolantie 8, 02100 Espoo', verificationStatus: 'VERIFIED', rating: 4.5, totalReviews: 67 },
  { id: 'vendor-004', userId: 'user-006', businessName: 'Sculpture Garden Collective', description: 'Outdoor sculpture park and workshop space for 3D art', category: 'ART', subCategory: 'Sculpture Park', contactEmail: 'info@sculpturegarden.fi', contactPhone: '+358402000003', website: 'https://sculpturegarden.fi', city: 'Espoo', lat: 60.2100, lng: 24.6500, streetAddress: 'Westendintie 55, 02160 Espoo', verificationStatus: 'VERIFIED', rating: 4.7, totalReviews: 42 },

  // --- SPORTS (2) ---
  { id: 'vendor-005', userId: 'user-007', businessName: 'Peak Performance Sports', description: 'Multi-sport facility with indoor courts, climbing walls, and fitness center', category: 'SPORTS', subCategory: 'Sports Complex', contactEmail: 'info@peakperformancesports.fi', contactPhone: '+358402000004', website: 'https://peakperformancesports.fi', city: 'Vantaa', lat: 60.2934, lng: 25.0377, streetAddress: 'Tikkurilantie 22, 01300 Vantaa', verificationStatus: 'VERIFIED', rating: 4.4, totalReviews: 103 },
  { id: 'vendor-006', userId: 'user-007', businessName: 'Ace Tennis Academy', description: 'Professional tennis coaching with indoor and outdoor courts', category: 'SPORTS', subCategory: 'Tennis Club', contactEmail: 'info@acetennis.fi', contactPhone: '+358402000004', website: 'https://acetennis.fi', city: 'Helsinki', lat: 60.1900, lng: 24.9600, streetAddress: 'Viikintie 12, 00560 Helsinki', verificationStatus: 'VERIFIED', rating: 4.9, totalReviews: 56 },

  // --- ACTIVITIES (2) ---
  { id: 'vendor-007', userId: 'user-008', businessName: 'Zen Garden Wellness', description: 'Wellness center offering yoga, meditation, and holistic health experiences', category: 'ACTIVITIES', subCategory: 'Wellness Center', contactEmail: 'info@zengarden.fi', contactPhone: '+358402000005', website: 'https://zengarden.fi', city: 'Helsinki', lat: 60.1666, lng: 24.9332, streetAddress: 'Bulevardi 17, 00120 Helsinki', verificationStatus: 'VERIFIED', rating: 4.8, totalReviews: 210 },
  { id: 'vendor-008', userId: 'user-008', businessName: 'Eventful Moments', description: 'Curated experiences from cooking classes to outdoor adventures', category: 'ACTIVITIES', subCategory: 'Experience Curator', contactEmail: 'info@eventfulmoments.fi', contactPhone: '+358402000005', website: 'https://eventfulmoments.fi', city: 'Helsinki', lat: 60.1700, lng: 24.9300, streetAddress: 'Albertinkatu 30, 00150 Helsinki', verificationStatus: 'VERIFIED', rating: 4.6, totalReviews: 88 },
];

// ======================== VENUES ========================
export interface SampleVenueData {
  id: string;
  vendorId: string;
  name: string;
  description: string;
  type: 'INDOOR' | 'OUTDOOR' | 'STUDIO' | 'GALLERY' | 'FIELD' | 'COURT' | 'OTHER';
  capacity: number;
  city: string;
  lat: number;
  lng: number;
  streetAddress: string;
  amenities: string[];
  hourlyRate: number;
}

export const SAMPLE_VENUES: SampleVenueData[] = [
  // LA Music Hall venues
  { id: 'venue-001', vendorId: 'vendor-001', name: 'Main Concert Hall', description: 'Grand concert hall with world-class acoustics and stage', type: 'INDOOR', capacity: 500, city: 'Helsinki', lat: 60.1699, lng: 24.9384, streetAddress: 'Mannerheimintie 13, 00100 Helsinki', amenities: ['Stage', 'Professional Sound System', 'Lighting Rig', 'Backstage Area', 'Bar', 'VIP Lounge'], hourlyRate: 250.0 },
  { id: 'venue-002', vendorId: 'vendor-001', name: 'Acoustic Lounge', description: 'Intimate venue for acoustic sets and singer-songwriter performances', type: 'INDOOR', capacity: 120, city: 'Helsinki', lat: 60.1705, lng: 24.9390, streetAddress: 'Mannerheimintie 13, 00100 Helsinki', amenities: ['Stage', 'Sound System', 'Mood Lighting', 'Bar'], hourlyRate: 120.0 },

  // Harmony Studios venues
  { id: 'venue-003', vendorId: 'vendor-002', name: 'Studio A — Live Room', description: 'Professional recording studio with live performance capability', type: 'STUDIO', capacity: 80, city: 'Helsinki', lat: 60.1733, lng: 24.9410, streetAddress: 'Fredrikinkatu 25, 00120 Helsinki', amenities: ['Recording Equipment', 'Stage', 'Soundproofing', 'Green Room', 'Kitchenette'], hourlyRate: 180.0 },
  { id: 'venue-004', vendorId: 'vendor-002', name: 'Rooftop Session Space', description: 'Open-air rooftop venue for summer music events', type: 'OUTDOOR', capacity: 150, city: 'Helsinki', lat: 60.1730, lng: 24.9415, streetAddress: 'Fredrikinkatu 25, 00120 Helsinki', amenities: ['Stage', 'Outdoor Sound System', 'Fairy Lights', 'Bar', 'Heat Lamps'], hourlyRate: 200.0 },

  // Canvas & Cork Gallery venues
  { id: 'venue-005', vendorId: 'vendor-003', name: 'Main Gallery', description: 'Bright, minimalist gallery space with movable walls', type: 'GALLERY', capacity: 200, city: 'Espoo', lat: 60.2055, lng: 24.6559, streetAddress: 'Tapiolantie 8, 02100 Espoo', amenities: ['Movable Walls', 'Track Lighting', 'Climate Control', 'Reception Desk', 'Wine Bar'], hourlyRate: 150.0 },
  { id: 'venue-006', vendorId: 'vendor-003', name: 'Workshop Studio', description: 'Hands-on art workshop space with sinks and worktables', type: 'STUDIO', capacity: 40, city: 'Espoo', lat: 60.2060, lng: 24.6565, streetAddress: 'Tapiolantie 8, 02100 Espoo', amenities: ['Worktables', 'Sinks', 'Easels', 'Storage Lockers', 'Projector'], hourlyRate: 90.0 },

  // Sculpture Garden Collective venues
  { id: 'venue-007', vendorId: 'vendor-004', name: 'Outdoor Sculpture Park', description: 'Beautiful outdoor garden showcasing large-scale sculptures', type: 'OUTDOOR', capacity: 500, city: 'Espoo', lat: 60.2100, lng: 24.6500, streetAddress: 'Westendintie 55, 02160 Espoo', amenities: ['Walking Paths', 'Benches', 'Information Plaques', 'Café', 'Gift Shop'], hourlyRate: 100.0 },
  { id: 'venue-008', vendorId: 'vendor-004', name: 'Indoor Workshop Hall', description: 'Large indoor space for sculpture workshops and exhibitions', type: 'INDOOR', capacity: 80, city: 'Espoo', lat: 60.2095, lng: 24.6505, streetAddress: 'Westendintie 55, 02160 Espoo', amenities: ['High Ceilings', 'Industrial Doors', 'Workbenches', 'Tool Library', 'Safety Equipment'], hourlyRate: 130.0 },

  // Peak Performance Sports venues
  { id: 'venue-009', vendorId: 'vendor-005', name: 'Main Sports Hall', description: 'Full-size indoor sports hall for basketball, volleyball, and events', type: 'INDOOR', capacity: 800, city: 'Vantaa', lat: 60.2934, lng: 25.0377, streetAddress: 'Tikkurilantie 22, 01300 Vantaa', amenities: ['Hardwood Floor', 'Bleachers', 'Scoreboard', 'Locker Rooms', 'Showers', 'Equipment Rental'], hourlyRate: 200.0 },
  { id: 'venue-010', vendorId: 'vendor-005', name: 'Climbing Arena', description: 'Indoor climbing facility with bouldering walls and rope routes', type: 'INDOOR', capacity: 100, city: 'Vantaa', lat: 60.2940, lng: 25.0380, streetAddress: 'Tikkurilantie 22, 01300 Vantaa', amenities: ['Bouldering Walls', 'Rope Routes', 'Crash Pads', 'Harness Rental', 'Training Area'], hourlyRate: 80.0 },

  // Ace Tennis Academy venues
  { id: 'venue-011', vendorId: 'vendor-006', name: 'Indoor Court 1', description: 'Professional indoor tennis court with premium surface', type: 'COURT', capacity: 50, city: 'Helsinki', lat: 60.1900, lng: 24.9600, streetAddress: 'Viikintie 12, 00560 Helsinki', amenities: ['Premium Court Surface', 'Lighting', 'Ball Machine', 'Seating Area'], hourlyRate: 60.0 },
  { id: 'venue-012', vendorId: 'vendor-006', name: 'Outdoor Clay Court', description: 'Red clay court with viewing area, open May-September', type: 'OUTDOOR', capacity: 80, city: 'Helsinki', lat: 60.1905, lng: 24.9610, streetAddress: 'Viikintie 12, 00560 Helsinki', amenities: ['Clay Surface', 'Viewing Bleachers', 'Water Station', 'Equipment Shop'], hourlyRate: 40.0 },

  // Zen Garden Wellness venues
  { id: 'venue-013', vendorId: 'vendor-007', name: 'Yoga Studio', description: 'Serene yoga studio with bamboo floors and natural light', type: 'STUDIO', capacity: 40, city: 'Helsinki', lat: 60.1666, lng: 24.9332, streetAddress: 'Bulevardi 17, 00120 Helsinki', amenities: ['Bamboo Floor', 'Yoga Mats', 'Blocks & Straps', 'Sound System', 'Essential Oil Diffusers'], hourlyRate: 70.0 },
  { id: 'venue-014', vendorId: 'vendor-007', name: 'Meditation Garden', description: 'Peaceful outdoor meditation garden with water features', type: 'OUTDOOR', capacity: 30, city: 'Helsinki', lat: 60.1670, lng: 24.9330, streetAddress: 'Bulevardi 17, 00120 Helsinki', amenities: ['Meditation Cushions', 'Water Feature', 'Zen Garden', 'Tea House', 'Walking Path'], hourlyRate: 50.0 },

  // Eventful Moments venues
  { id: 'venue-015', vendorId: 'vendor-008', name: 'Culinary Workshop Kitchen', description: 'Professional teaching kitchen for cooking classes and food events', type: 'INDOOR', capacity: 24, city: 'Helsinki', lat: 60.1700, lng: 24.9300, streetAddress: 'Albertinkatu 30, 00150 Helsinki', amenities: ['Induction Cooktops', 'Ovens', 'Refrigeration', 'Dining Area', 'Wine Fridge'], hourlyRate: 120.0 },
  { id: 'venue-016', vendorId: 'vendor-008', name: 'Adventure Basecamp', description: 'Starting point for outdoor adventures and team-building activities', type: 'OUTDOOR', capacity: 60, city: 'Helsinki', lat: 60.1710, lng: 24.9290, streetAddress: 'Albertinkatu 30, 00150 Helsinki', amenities: ['Equipment Storage', 'Briefing Room', 'Lockers', 'First Aid Station', 'BBQ Area'], hourlyRate: 90.0 },
];

// ======================== EVENTS ========================
export interface SampleEventData {
  id: string;
  vendorId: string;
  venueId: string;
  title: string;
  description: string;
  category: 'MUSIC' | 'ART' | 'SPORTS' | 'ACTIVITIES' | 'OTHER';
  subCategory: string;
  startTime: string;
  endTime: string;
  city: string;
  lat: number;
  lng: number;
  price: { general?: number; vip?: number; student?: number; currency: string };
  pricingModel: 'FREE' | 'PER_HOUR' | 'CONTRACT' | 'MIXED';
  maxAttendees: number;
  currentBookings: number;
  status: 'DRAFT' | 'PUBLISHED' | 'CANCELLED' | 'COMPLETED' | 'POSTPONED';
  tags: string[];
  ageRestriction: number | null;
  isRecurring: boolean;
  recurringRule: string | null;
}

export const SAMPLE_EVENTS: SampleEventData[] = [
  // ===== MUSIC EVENTS (12) =====
  // --- Published / Upcoming ---
  { id: 'event-001', vendorId: 'vendor-001', venueId: 'venue-001', title: 'Jazz Night Live', description: 'An evening of smooth jazz featuring the Helsinki Jazz Quartet and special guests. Enjoy classic standards and original compositions in our main hall.', category: 'MUSIC', subCategory: 'Jazz', startTime: '2026-06-15T19:00:00Z', endTime: '2026-06-15T23:00:00Z', city: 'Helsinki', lat: 60.1699, lng: 24.9384, price: { general: 25.0, vip: 50.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 500, currentBookings: 245, status: 'PUBLISHED', tags: ['jazz', 'live music', 'weekend'], ageRestriction: 18, isRecurring: false, recurringRule: null },
  { id: 'event-002', vendorId: 'vendor-001', venueId: 'venue-002', title: 'Acoustic Fridays: Singer-Songwriter Night', description: 'Intimate acoustic performances by up-and-coming Finnish singer-songwriters. Every Friday in the Acoustic Lounge.', category: 'MUSIC', subCategory: 'Acoustic', startTime: '2026-06-20T20:00:00Z', endTime: '2026-06-20T23:00:00Z', city: 'Helsinki', lat: 60.1705, lng: 24.9390, price: { general: 15.0, student: 10.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 120, currentBookings: 78, status: 'PUBLISHED', tags: ['acoustic', 'folk', 'friday', 'local artists'], ageRestriction: null, isRecurring: true, recurringRule: 'WEEKLY' },
  { id: 'event-003', vendorId: 'vendor-002', venueId: 'venue-003', title: 'Electronic Music Production Workshop', description: 'Learn electronic music production techniques from professional producers. Hands-on session with Ableton Live, hardware synths, and mixing techniques.', category: 'MUSIC', subCategory: 'Music Production', startTime: '2026-06-25T14:00:00Z', endTime: '2026-06-25T18:00:00Z', city: 'Helsinki', lat: 60.1733, lng: 24.9410, price: { general: 45.0, student: 30.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 30, currentBookings: 22, status: 'PUBLISHED', tags: ['electronic', 'production', 'workshop', 'ableton'], ageRestriction: 16, isRecurring: false, recurringRule: null },
  { id: 'event-004', vendorId: 'vendor-002', venueId: 'venue-004', title: 'Summer Rooftop Sessions: Indie Bands', description: 'Enjoy the Helsinki summer sunset with live indie bands on our rooftop. Drinks, music, and great vibes.', category: 'MUSIC', subCategory: 'Indie', startTime: '2026-07-05T18:00:00Z', endTime: '2026-07-05T22:00:00Z', city: 'Helsinki', lat: 60.1730, lng: 24.9415, price: { general: 20.0, student: 12.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 150, currentBookings: 110, status: 'PUBLISHED', tags: ['rooftop', 'indie', 'summer', 'bands'], ageRestriction: 18, isRecurring: false, recurringRule: null },

  // --- Past / Completed ---
  { id: 'event-005', vendorId: 'vendor-001', venueId: 'venue-001', title: 'Classical Night: Sibelius & Beyond', description: 'The Helsinki Philharmonic performs Sibelius symphonies and modern Finnish classical works.', category: 'MUSIC', subCategory: 'Classical', startTime: '2026-04-10T19:00:00Z', endTime: '2026-04-10T22:00:00Z', city: 'Helsinki', lat: 60.1699, lng: 24.9384, price: { general: 35.0, vip: 70.0, student: 15.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 500, currentBookings: 480, status: 'COMPLETED', tags: ['classical', 'sibelius', 'orchestra'], ageRestriction: null, isRecurring: false, recurringRule: null },
  { id: 'event-006', vendorId: 'vendor-001', venueId: 'venue-002', title: 'Blues & Bourbon Night', description: 'Deep south blues paired with curated bourbon tasting. Featuring the Dirty Fingers Blues Band.', category: 'MUSIC', subCategory: 'Blues', startTime: '2026-04-25T20:00:00Z', endTime: '2026-04-26T01:00:00Z', city: 'Helsinki', lat: 60.1705, lng: 24.9390, price: { general: 30.0, vip: 55.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 120, currentBookings: 120, status: 'COMPLETED', tags: ['blues', 'bourbon', 'tasting'], ageRestriction: 21, isRecurring: false, recurringRule: null },
  { id: 'event-007', vendorId: 'vendor-002', venueId: 'venue-003', title: 'Rock Guitar Workshop', description: 'Learn rock guitar techniques from professional musicians. Covers lead guitar, rhythm, tone shaping, and soloing. All skill levels welcome.', category: 'MUSIC', subCategory: 'Music Education', startTime: '2026-04-18T10:00:00Z', endTime: '2026-04-18T16:00:00Z', city: 'Helsinki', lat: 60.1733, lng: 24.9410, price: { general: 40.0, student: 25.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 30, currentBookings: 28, status: 'COMPLETED', tags: ['workshop', 'guitar', 'rock', 'education'], ageRestriction: 14, isRecurring: true, recurringRule: 'MONTHLY' },
  { id: 'event-008', vendorId: 'vendor-002', venueId: 'venue-004', title: 'Techno Underground', description: 'Late-night techno party featuring Berlin-based DJs and immersive light installations.', category: 'MUSIC', subCategory: 'Electronic', startTime: '2026-05-03T22:00:00Z', endTime: '2026-05-04T04:00:00Z', city: 'Helsinki', lat: 60.1730, lng: 24.9415, price: { general: 22.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 150, currentBookings: 145, status: 'COMPLETED', tags: ['techno', 'electronic', 'late night', 'DJ'], ageRestriction: 20, isRecurring: false, recurringRule: null },

  // --- Draft / Upcoming ---
  { id: 'event-009', vendorId: 'vendor-001', venueId: 'venue-001', title: 'Summer Music Festival 2026', description: 'Two-day outdoor-to-indoor festival featuring 20+ bands across 2 stages. Food trucks, art installations, and camping options.', category: 'MUSIC', subCategory: 'Festival', startTime: '2026-07-25T14:00:00Z', endTime: '2026-07-26T23:00:00Z', city: 'Helsinki', lat: 60.1699, lng: 24.9384, price: { general: 85.0, vip: 150.0, student: 55.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 500, currentBookings: 320, status: 'PUBLISHED', tags: ['festival', 'summer', 'multi-day', 'food trucks'], ageRestriction: 18, isRecurring: false, recurringRule: null },
  { id: 'event-010', vendorId: 'vendor-001', venueId: 'venue-001', title: 'New Year Gala Concert', description: 'Elegant New Year celebration with waltz orchestra, champagne, and fireworks viewing from our balcony.', category: 'MUSIC', subCategory: 'Classical', startTime: '2026-12-31T20:00:00Z', endTime: '2027-01-01T01:00:00Z', city: 'Helsinki', lat: 60.1699, lng: 24.9384, price: { general: 120.0, vip: 200.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 500, currentBookings: 150, status: 'PUBLISHED', tags: ['new year', 'gala', 'classical', 'champagne'], ageRestriction: 18, isRecurring: false, recurringRule: null },
  { id: 'event-011', vendorId: 'vendor-002', venueId: 'venue-003', title: 'Vinyl Listening Party', description: 'Bring your favorite records and discover new ones. Analog listening on high-end equipment with fellow audiophiles.', category: 'MUSIC', subCategory: 'Listening Party', startTime: '2026-05-20T19:00:00Z', endTime: '2026-05-20T22:00:00Z', city: 'Helsinki', lat: 60.1733, lng: 24.9410, price: { general: 0.0, currency: 'EUR' }, pricingModel: 'FREE', maxAttendees: 80, currentBookings: 65, status: 'COMPLETED', tags: ['vinyl', 'listening party', 'audiophile', 'free'], ageRestriction: null, isRecurring: true, recurringRule: 'MONTHLY' },
  { id: 'event-012', vendorId: 'vendor-002', venueId: 'venue-003', title: 'Songwriting Masterclass', description: 'Intensive songwriting workshop with Grammy-nominated songwriter. Limited to 20 participants for focused mentoring.', category: 'MUSIC', subCategory: 'Masterclass', startTime: '2026-07-10T10:00:00Z', endTime: '2026-07-10T17:00:00Z', city: 'Helsinki', lat: 60.1733, lng: 24.9410, price: { general: 150.0, student: 100.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 20, currentBookings: 8, status: 'PUBLISHED', tags: ['masterclass', 'songwriting', 'mentoring'], ageRestriction: 16, isRecurring: false, recurringRule: null },

  // ===== ART EVENTS (8) =====
  { id: 'event-013', vendorId: 'vendor-003', venueId: 'venue-005', title: 'Nordic Contemporary Art Exhibition', description: 'Showcasing the best of Nordic contemporary art: paintings, installations, and mixed media from 15 emerging artists.', category: 'ART', subCategory: 'Exhibition', startTime: '2026-06-01T10:00:00Z', endTime: '2026-06-30T18:00:00Z', city: 'Espoo', lat: 60.2055, lng: 24.6559, price: { general: 12.0, student: 6.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 200, currentBookings: 85, status: 'PUBLISHED', tags: ['contemporary', 'nordic', 'exhibition', 'painting'], ageRestriction: null, isRecurring: false, recurringRule: null },
  { id: 'event-014', vendorId: 'vendor-003', venueId: 'venue-006', title: 'Watercolor Workshop for Beginners', description: 'Learn watercolor painting basics in a relaxed, supportive environment. All materials provided.', category: 'ART', subCategory: 'Workshop', startTime: '2026-06-14T13:00:00Z', endTime: '2026-06-14T16:00:00Z', city: 'Espoo', lat: 60.2060, lng: 24.6565, price: { general: 35.0, student: 25.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 40, currentBookings: 32, status: 'PUBLISHED', tags: ['watercolor', 'beginner', 'workshop', 'painting'], ageRestriction: 12, isRecurring: true, recurringRule: 'WEEKLY' },
  { id: 'event-015', vendorId: 'vendor-004', venueId: 'venue-007', title: 'Sculpture in the Park: Summer Exhibition', description: 'Annual outdoor sculpture exhibition set in our beautiful sculpture park. Featuring large-scale works by Finnish sculptors.', category: 'ART', subCategory: 'Exhibition', startTime: '2026-06-15T10:00:00Z', endTime: '2026-08-31T20:00:00Z', city: 'Espoo', lat: 60.2100, lng: 24.6500, price: { general: 0.0, currency: 'EUR' }, pricingModel: 'FREE', maxAttendees: 500, currentBookings: 0, status: 'PUBLISHED', tags: ['sculpture', 'outdoor', 'summer', 'free'], ageRestriction: null, isRecurring: false, recurringRule: null },
  { id: 'event-016', vendorId: 'vendor-004', venueId: 'venue-008', title: 'Stone Carving Intensive', description: 'Three-day intensive stone carving workshop. Learn traditional and modern techniques from master sculptor Eero Mäntynen.', category: 'ART', subCategory: 'Workshop', startTime: '2026-07-15T09:00:00Z', endTime: '2026-07-17T17:00:00Z', city: 'Espoo', lat: 60.2095, lng: 24.6505, price: { general: 280.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 12, currentBookings: 6, status: 'PUBLISHED', tags: ['stone carving', 'sculpture', 'intensive', 'masterclass'], ageRestriction: 18, isRecurring: false, recurringRule: null },
  { id: 'event-017', vendorId: 'vendor-003', venueId: 'venue-005', title: 'Photography Exhibition: Helsinki Streets', description: 'Street photography capturing the essence of Helsinki neighborhoods through the seasons.', category: 'ART', subCategory: 'Photography', startTime: '2026-04-05T11:00:00Z', endTime: '2026-05-15T18:00:00Z', city: 'Espoo', lat: 60.2055, lng: 24.6559, price: { general: 8.0, student: 4.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 200, currentBookings: 190, status: 'COMPLETED', tags: ['photography', 'helsinki', 'street', 'exhibition'], ageRestriction: null, isRecurring: false, recurringRule: null },
  { id: 'event-018', vendorId: 'vendor-003', venueId: 'venue-006', title: 'Pottery & Wine Evening', description: 'Relaxed evening of pottery making with wine and cheese. No experience needed — create your own ceramic piece.', category: 'ART', subCategory: 'Social', startTime: '2026-05-08T18:00:00Z', endTime: '2026-05-08T21:00:00Z', city: 'Espoo', lat: 60.2060, lng: 24.6565, price: { general: 45.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 30, currentBookings: 30, status: 'COMPLETED', tags: ['pottery', 'wine', 'social', 'beginner'], ageRestriction: 18, isRecurring: true, recurringRule: 'MONTHLY' },
  { id: 'event-019', vendorId: 'vendor-004', venueId: 'venue-008', title: 'Metal Art Welding Workshop', description: 'Introduction to metal art and welding. Create your own metal sculpture under expert supervision. Safety gear provided.', category: 'ART', subCategory: 'Workshop', startTime: '2026-07-22T10:00:00Z', endTime: '2026-07-22T16:00:00Z', city: 'Espoo', lat: 60.2095, lng: 24.6505, price: { general: 95.0, student: 70.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 15, currentBookings: 5, status: 'PUBLISHED', tags: ['welding', 'metal art', 'workshop', 'sculpture'], ageRestriction: 18, isRecurring: false, recurringRule: null },
  { id: 'event-020', vendorId: 'vendor-003', venueId: 'venue-005', title: 'Art After Dark: Neon & Light Installations', description: 'Evening exhibition of immersive light art and neon installations. Interactive pieces, ambient music, and cocktails.', category: 'ART', subCategory: 'Exhibition', startTime: '2026-05-30T20:00:00Z', endTime: '2026-05-31T01:00:00Z', city: 'Espoo', lat: 60.2055, lng: 24.6559, price: { general: 18.0, vip: 35.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 200, currentBookings: 200, status: 'COMPLETED', tags: ['light art', 'neon', 'night', 'immersive'], ageRestriction: 18, isRecurring: false, recurringRule: null },

  // ===== SPORTS EVENTS (10) =====
  { id: 'event-021', vendorId: 'vendor-005', venueId: 'venue-009', title: '3v3 Basketball Tournament', description: 'Fast-paced 3-on-3 street basketball tournament. Team registration, prizes for winners, and after-party.', category: 'SPORTS', subCategory: 'Basketball', startTime: '2026-07-12T10:00:00Z', endTime: '2026-07-12T18:00:00Z', city: 'Vantaa', lat: 60.2934, lng: 25.0377, price: { general: 25.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 800, currentBookings: 320, status: 'PUBLISHED', tags: ['basketball', 'tournament', '3v3', 'team'], ageRestriction: 14, isRecurring: false, recurringRule: null },
  { id: 'event-022', vendorId: 'vendor-005', venueId: 'venue-010', title: 'Beginner Bouldering Clinic', description: 'Introduction to bouldering: technique, safety, and route reading. No experience required. Includes day pass.', category: 'SPORTS', subCategory: 'Climbing', startTime: '2026-06-28T14:00:00Z', endTime: '2026-06-28T17:00:00Z', city: 'Vantaa', lat: 60.2940, lng: 25.0380, price: { general: 30.0, student: 20.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 30, currentBookings: 18, status: 'PUBLISHED', tags: ['bouldering', 'climbing', 'beginner', 'clinic'], ageRestriction: 10, isRecurring: true, recurringRule: 'WEEKLY' },
  { id: 'event-023', vendorId: 'vendor-006', venueId: 'venue-011', title: 'Adult Tennis League — Spring 2026', description: 'Competitive adult tennis league. 8-week season with playoffs. Doubles and singles divisions.', category: 'SPORTS', subCategory: 'Tennis', startTime: '2026-04-01T18:00:00Z', endTime: '2026-05-31T21:00:00Z', city: 'Helsinki', lat: 60.1900, lng: 24.9600, price: { general: 120.0, student: 80.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 50, currentBookings: 50, status: 'COMPLETED', tags: ['tennis', 'league', 'competitive', 'season'], ageRestriction: 18, isRecurring: false, recurringRule: null },
  { id: 'event-024', vendorId: 'vendor-006', venueId: 'venue-012', title: 'Kids Summer Tennis Camp', description: 'Week-long tennis camp for kids ages 7-14. Coaching, games, swimming, and lunch included.', category: 'SPORTS', subCategory: 'Tennis', startTime: '2026-07-06T09:00:00Z', endTime: '2026-07-10T15:00:00Z', city: 'Helsinki', lat: 60.1905, lng: 24.9610, price: { general: 200.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 40, currentBookings: 25, status: 'PUBLISHED', tags: ['tennis', 'kids', 'camp', 'summer'], ageRestriction: null, isRecurring: false, recurringRule: null },
  { id: 'event-025', vendorId: 'vendor-005', venueId: 'venue-009', title: 'Volleyball Open Play', description: 'Casual volleyball for all skill levels. Rotating teams, friendly atmosphere. Drop in any time.', category: 'SPORTS', subCategory: 'Volleyball', startTime: '2026-06-17T19:00:00Z', endTime: '2026-06-17T22:00:00Z', city: 'Vantaa', lat: 60.2934, lng: 25.0377, price: { general: 10.0, currency: 'EUR' }, pricingModel: 'PER_HOUR', maxAttendees: 100, currentBookings: 45, status: 'PUBLISHED', tags: ['volleyball', 'casual', 'open play', 'drop-in'], ageRestriction: null, isRecurring: true, recurringRule: 'WEEKLY' },
  { id: 'event-026', vendorId: 'vendor-005', venueId: 'venue-009', title: 'Corporate Sports Day', description: 'Team building through sports: relay races, tug-of-war, dodgeball, and more. Catering and medals included.', category: 'SPORTS', subCategory: 'Team Building', startTime: '2026-04-22T09:00:00Z', endTime: '2026-04-22T17:00:00Z', city: 'Vantaa', lat: 60.2934, lng: 25.0377, price: { general: 0.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 200, currentBookings: 180, status: 'COMPLETED', tags: ['corporate', 'team building', 'sports day'], ageRestriction: 18, isRecurring: false, recurringRule: null },
  { id: 'event-027', vendorId: 'vendor-006', venueId: 'venue-011', title: 'Tennis Doubles Social', description: 'Social doubles tennis with rotating partners. Pizza and drinks afterward. Great way to meet other players.', category: 'SPORTS', subCategory: 'Tennis', startTime: '2026-06-11T18:00:00Z', endTime: '2026-06-11T21:00:00Z', city: 'Helsinki', lat: 60.1900, lng: 24.9600, price: { general: 20.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 32, currentBookings: 20, status: 'PUBLISHED', tags: ['tennis', 'doubles', 'social', 'pizza'], ageRestriction: 16, isRecurring: true, recurringRule: 'MONTHLY' },
  { id: 'event-028', vendorId: 'vendor-005', venueId: 'venue-010', title: 'Advanced Lead Climbing Course', description: 'Intensive lead climbing course for experienced climbers. Covers advanced techniques, fall practice, and route setting.', category: 'SPORTS', subCategory: 'Climbing', startTime: '2026-07-19T10:00:00Z', endTime: '2026-07-19T17:00:00Z', city: 'Vantaa', lat: 60.2940, lng: 25.0380, price: { general: 85.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 12, currentBookings: 7, status: 'PUBLISHED', tags: ['climbing', 'lead', 'advanced', 'course'], ageRestriction: 16, isRecurring: false, recurringRule: null },
  { id: 'event-029', vendorId: 'vendor-006', venueId: 'venue-011', title: 'Parent-Child Tennis Fun Day', description: 'Fun tennis activities for parents and children. Games, drills, and a mini-tournament. Rackets provided if needed.', category: 'SPORTS', subCategory: 'Tennis', startTime: '2026-05-17T10:00:00Z', endTime: '2026-05-17T14:00:00Z', city: 'Helsinki', lat: 60.1900, lng: 24.9600, price: { general: 15.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 40, currentBookings: 35, status: 'COMPLETED', tags: ['tennis', 'family', 'kids', 'fun'], ageRestriction: null, isRecurring: false, recurringRule: null },
  { id: 'event-030', vendorId: 'vendor-005', venueId: 'venue-009', title: 'Summer Basketball Camp', description: 'Intensive basketball camp for teens. Professional coaching, skill development, scrimmages, and guest pro appearances.', category: 'SPORTS', subCategory: 'Basketball', startTime: '2026-07-27T09:00:00Z', endTime: '2026-07-31T16:00:00Z', city: 'Vantaa', lat: 60.2934, lng: 25.0377, price: { general: 180.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 60, currentBookings: 28, status: 'PUBLISHED', tags: ['basketball', 'camp', 'teens', 'summer'], ageRestriction: null, isRecurring: false, recurringRule: null },

  // ===== ACTIVITIES EVENTS (10) =====
  { id: 'event-031', vendorId: 'vendor-007', venueId: 'venue-013', title: 'Morning Yoga Flow', description: 'Start your day with an energizing vinyasa flow. Suitable for all levels. Mats provided.', category: 'ACTIVITIES', subCategory: 'Yoga', startTime: '2026-06-16T07:00:00Z', endTime: '2026-06-16T08:15:00Z', city: 'Helsinki', lat: 60.1666, lng: 24.9332, price: { general: 15.0, student: 10.0, currency: 'EUR' }, pricingModel: 'PER_HOUR', maxAttendees: 40, currentBookings: 25, status: 'PUBLISHED', tags: ['yoga', 'morning', 'vinyasa', 'wellness'], ageRestriction: null, isRecurring: true, recurringRule: 'DAILY' },
  { id: 'event-032', vendorId: 'vendor-007', venueId: 'venue-014', title: 'Guided Meditation & Sound Bath', description: 'Deep relaxation through guided meditation and crystal singing bowl sound bath in our peaceful garden.', category: 'ACTIVITIES', subCategory: 'Meditation', startTime: '2026-06-18T18:00:00Z', endTime: '2026-06-18T19:30:00Z', city: 'Helsinki', lat: 60.1670, lng: 24.9330, price: { general: 20.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 30, currentBookings: 18, status: 'PUBLISHED', tags: ['meditation', 'sound bath', 'relaxation', 'garden'], ageRestriction: null, isRecurring: true, recurringRule: 'WEEKLY' },
  { id: 'event-033', vendorId: 'vendor-008', venueId: 'venue-015', title: 'Finnish Cuisine Cooking Class', description: 'Learn to make traditional Finnish dishes: salmon soup, Karelian pies, and cinnamon buns. Dinner and wine included.', category: 'ACTIVITIES', subCategory: 'Cooking', startTime: '2026-06-22T17:00:00Z', endTime: '2026-06-22T21:00:00Z', city: 'Helsinki', lat: 60.1700, lng: 24.9300, price: { general: 65.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 24, currentBookings: 18, status: 'PUBLISHED', tags: ['cooking', 'finnish', 'cuisine', 'food'], ageRestriction: 16, isRecurring: true, recurringRule: 'WEEKLY' },
  { id: 'event-034', vendorId: 'vendor-008', venueId: 'venue-016', title: 'Forest Foraging & Wild Food Walk', description: 'Guided foraging walk in Nuuksio National Park. Learn to identify edible mushrooms, berries, and herbs. Picnic lunch included.', category: 'ACTIVITIES', subCategory: 'Outdoor', startTime: '2026-07-05T09:00:00Z', endTime: '2026-07-05T14:00:00Z', city: 'Helsinki', lat: 60.1710, lng: 24.9290, price: { general: 40.0, student: 30.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 20, currentBookings: 12, status: 'PUBLISHED', tags: ['foraging', 'forest', 'wild food', 'outdoor'], ageRestriction: 12, isRecurring: false, recurringRule: null },
  { id: 'event-035', vendorId: 'vendor-007', venueId: 'venue-013', title: 'Prenatal Yoga Series', description: 'Gentle yoga for expecting mothers. Focus on breathing, stretching, and preparation for childbirth. 6-week series.', category: 'ACTIVITIES', subCategory: 'Yoga', startTime: '2026-04-08T10:00:00Z', endTime: '2026-05-13T11:30:00Z', city: 'Helsinki', lat: 60.1666, lng: 24.9332, price: { general: 120.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 20, currentBookings: 16, status: 'COMPLETED', tags: ['prenatal', 'yoga', 'pregnancy', 'wellness'], ageRestriction: 18, isRecurring: false, recurringRule: null },
  { id: 'event-036', vendorId: 'vendor-008', venueId: 'venue-015', title: 'Sourdough Bread Baking Workshop', description: 'Master the art of sourdough: starter maintenance, kneading, shaping, and baking. Take home your own starter and fresh bread.', category: 'ACTIVITIES', subCategory: 'Baking', startTime: '2026-05-24T10:00:00Z', endTime: '2026-05-24T15:00:00Z', city: 'Helsinki', lat: 60.1700, lng: 24.9300, price: { general: 55.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 16, currentBookings: 16, status: 'COMPLETED', tags: ['sourdough', 'baking', 'bread', 'workshop'], ageRestriction: 14, isRecurring: true, recurringRule: 'MONTHLY' },
  { id: 'event-037', vendorId: 'vendor-007', venueId: 'venue-014', title: 'Full Moon Yoga & Cacao Ceremony', description: 'Special full moon celebration: gentle yoga, cacao ceremony, intention setting, and fire pit gathering.', category: 'ACTIVITIES', subCategory: 'Ceremony', startTime: '2026-07-08T20:00:00Z', endTime: '2026-07-08T23:00:00Z', city: 'Helsinki', lat: 60.1670, lng: 24.9330, price: { general: 35.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 30, currentBookings: 22, status: 'PUBLISHED', tags: ['full moon', 'yoga', 'cacao', 'ceremony'], ageRestriction: 16, isRecurring: false, recurringRule: null },
  { id: 'event-038', vendorId: 'vendor-008', venueId: 'venue-016', title: 'Kayaking Adventure: Helsinki Archipelago', description: 'Guided sea kayaking trip through the Helsinki archipelago. Suitable for beginners. All equipment and lunch provided.', category: 'ACTIVITIES', subCategory: 'Adventure', startTime: '2026-07-15T09:00:00Z', endTime: '2026-07-15T17:00:00Z', city: 'Helsinki', lat: 60.1710, lng: 24.9290, price: { general: 75.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 16, currentBookings: 10, status: 'PUBLISHED', tags: ['kayaking', 'archipelago', 'adventure', 'outdoor'], ageRestriction: 14, isRecurring: true, recurringRule: 'WEEKLY' },
  { id: 'event-039', vendorId: 'vendor-008', venueId: 'venue-015', title: 'Wine Tasting: European Reds', description: 'Guided tasting of 8 premium European red wines paired with artisan cheeses. Led by certified sommelier.', category: 'ACTIVITIES', subCategory: 'Wine Tasting', startTime: '2026-05-29T19:00:00Z', endTime: '2026-05-29T22:00:00Z', city: 'Helsinki', lat: 60.1700, lng: 24.9300, price: { general: 55.0, vip: 80.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 24, currentBookings: 24, status: 'COMPLETED', tags: ['wine', 'tasting', 'european', 'cheese'], ageRestriction: 20, isRecurring: true, recurringRule: 'MONTHLY' },
  { id: 'event-040', vendorId: 'vendor-007', venueId: 'venue-013', title: 'Weekend Wellness Retreat', description: 'Full weekend of yoga, meditation, breathwork, and healthy meals. Reset your mind and body in our serene space.', category: 'ACTIVITIES', subCategory: 'Retreat', startTime: '2026-07-18T09:00:00Z', endTime: '2026-07-19T17:00:00Z', city: 'Helsinki', lat: 60.1666, lng: 24.9332, price: { general: 250.0, currency: 'EUR' }, pricingModel: 'CONTRACT', maxAttendees: 24, currentBookings: 14, status: 'PUBLISHED', tags: ['retreat', 'wellness', 'weekend', 'yoga'], ageRestriction: 16, isRecurring: false, recurringRule: null },
];
