apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NODE_ENV: "production"
  KAFKA_BROKERS: "kafka-service:9092"
  ELASTICSEARCH_HOSTS: "http://elasticsearch-service:9200"
  LOG_LEVEL: "info"
  AUTH_SERVICE_URL: "http://auth-service:3000"
  USER_SERVICE_URL: "http://user-service:3000"
  VENDOR_SERVICE_URL: "http://vendor-service:3000"
  EVENT_SERVICE_URL: "http://event-service:3000"
