-- ============================================
-- Sample Users Migration
-- Inserts 25 users into auth_db.users table
-- Run: psql $AUTH_DATABASE_URL -f this_file.sql
-- ============================================

-- Passwords are all bcrypt hashes of the actual passwords:
-- user123  -> $2a$10$... (all regular users)
-- Three1288 -> $2a$10$... (pahakadmin)
-- admin123  -> $2a$10$... (admin)
-- vendor123 -> $2a$10$... (vendors)
-- Use the seed.ts script for properly hashed passwords.
-- This SQL file uses placeholder hashes — use seed.ts for real data.

INSERT INTO users (id, email, password, first_name, last_name, phone, role, location, preferences, created_at, updated_at) VALUES
('user-001', 'pahakadmin@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Pahak', 'Admin', '+358401000001', 'ADMIN', '{"city":"Helsinki","country":"Finland","latitude":60.1699,"longitude":24.9384}', '{"musicalGenres":[],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":50}', NOW(), NOW()),
('user-002', 'admin@example.com', '$2a$10$PLACEHOLDER_HASH', 'Admin', 'User', '+358401000002', 'ADMIN', '{"city":"Helsinki","country":"Finland","latitude":60.1699,"longitude":24.9384}', '{"musicalGenres":[],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":50}', NOW(), NOW()),
('user-003', 'ops@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Ops', 'Manager', '+358401000003', 'ADMIN', '{"city":"Espoo","country":"Finland","latitude":60.2055,"longitude":24.6559}', '{"musicalGenres":[],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":50}', NOW(), NOW()),
('user-004', 'vendor@example.com', '$2a$10$PLACEHOLDER_HASH', 'Venue', 'Owner', '+358402000001', 'VENDOR', '{"city":"Helsinki","country":"Finland","latitude":60.1699,"longitude":24.9384}', '{"musicalGenres":["jazz","classical"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":30}', NOW(), NOW()),
('user-005', 'harmony@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Mika', 'Virtanen', '+358402000002', 'VENDOR', '{"city":"Helsinki","country":"Finland","latitude":60.1733,"longitude":24.9410}', '{"musicalGenres":["rock","pop","electronic"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":25}', NOW(), NOW()),
('user-006', 'gallery@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Sofia', 'Korhonen', '+358402000003', 'VENDOR', '{"city":"Espoo","country":"Finland","latitude":60.2055,"longitude":24.6559}', '{"musicalGenres":[],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":40}', NOW(), NOW()),
('user-007', 'sports@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Jani', 'Mäkinen', '+358402000004', 'VENDOR', '{"city":"Vantaa","country":"Finland","latitude":60.2934,"longitude":25.0377}', '{"musicalGenres":[],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":35}', NOW(), NOW()),
('user-008', 'activities@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Emma', 'Nieminen', '+358402000005', 'VENDOR', '{"city":"Helsinki","country":"Finland","latitude":60.1666,"longitude":24.9332}', '{"musicalGenres":[],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":20}', NOW(), NOW()),
('user-009', 'user@example.com', '$2a$10$PLACEHOLDER_HASH', 'Music', 'Lover', '+358403000001', 'USER', '{"city":"Helsinki","country":"Finland","latitude":60.1699,"longitude":24.9384}', '{"musicalGenres":["jazz","blues","soul"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":30}', NOW(), NOW()),
('user-010', 'anna@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Anna', 'Järvinen', '+358403000002', 'USER', '{"city":"Helsinki","country":"Finland","latitude":60.1720,"longitude":24.9450}', '{"musicalGenres":["rock","metal","punk"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":50}', NOW(), NOW()),
('user-011', 'mikko@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Mikko', 'Lahtinen', '+358403000003', 'USER', '{"city":"Espoo","country":"Finland","latitude":60.2055,"longitude":24.6559}', '{"musicalGenres":[],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":25}', NOW(), NOW()),
('user-012', 'liisa@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Liisa', 'Hämäläinen', '+358403000004', 'USER', '{"city":"Vantaa","country":"Finland","latitude":60.2934,"longitude":25.0377}', '{"musicalGenres":["pop","hip-hop"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":35}', NOW(), NOW()),
('user-013', 'juha@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Juha', 'Salonen', '+358403000005', 'USER', '{"city":"Helsinki","country":"Finland","latitude":60.1670,"longitude":24.9350}', '{"musicalGenres":["ambient","classical"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":15}', NOW(), NOW()),
('user-014', 'pekka@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Pekka', 'Heikkinen', '+358403000006', 'USER', '{"city":"Tampere","country":"Finland","latitude":61.4978,"longitude":23.7610}', '{"musicalGenres":["electronic","techno","house"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":40}', NOW(), NOW()),
('user-015', 'elina@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Elina', 'Koskinen', '+358403000007', 'USER', '{"city":"Turku","country":"Finland","latitude":60.4518,"longitude":22.2666}', '{"musicalGenres":["classical","opera"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":30}', NOW(), NOW()),
('user-016', 'tommi@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Tommi', 'Lehtonen', '+358403000008', 'USER', '{"city":"Helsinki","country":"Finland","latitude":60.1800,"longitude":24.9500}', '{"musicalGenres":["rock","pop"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":20}', NOW(), NOW()),
('user-017', 'sanna@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Sanna', 'Rantanen', '+358403000009', 'USER', '{"city":"Espoo","country":"Finland","latitude":60.2100,"longitude":24.6600}', '{"musicalGenres":["folk","indie"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":25}', NOW(), NOW()),
('user-018', 'ville@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Ville', 'Aaltonen', '+358403000010', 'USER', '{"city":"Helsinki","country":"Finland","latitude":60.1630,"longitude":24.9280}', '{"musicalGenres":["jazz","bossa nova"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":20}', NOW(), NOW()),
('user-019', 'kati@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Kati', 'Peltola', '+358403000011', 'USER', '{"city":"Oulu","country":"Finland","latitude":65.0121,"longitude":25.4651}', '{"musicalGenres":["indie","alternative","folk"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":50}', NOW(), NOW()),
('user-020', 'markus@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Markus', 'Saarinen', '+358403000012', 'USER', '{"city":"Helsinki","country":"Finland","latitude":60.1710,"longitude":24.9420}', '{"musicalGenres":["hip-hop","rap"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":15}', NOW(), NOW()),
('user-021', 'jenni@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Jenni', 'Tuominen', '+358403000013', 'USER', '{"city":"Lahti","country":"Finland","latitude":60.9827,"longitude":25.6612}', '{"musicalGenres":["classical","jazz"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":40}', NOW(), NOW()),
('user-022', 'olli@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Olli', 'Mäkelä', '+358403000014', 'USER', '{"city":"Helsinki","country":"Finland","latitude":60.1750,"longitude":24.9370}', '{"musicalGenres":["rock","electronic"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":20}', NOW(), NOW()),
('user-023', 'riikka@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Riikka', 'Kivi', '+358403000015', 'USER', '{"city":"Jyväskylä","country":"Finland","latitude":62.2426,"longitude":25.7473}', '{"musicalGenres":["pop","rock","electronic"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":100}', NOW(), NOW()),
('user-024', 'antti@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Antti', 'Kallio', '+358403000016', 'USER', '{"city":"Helsinki","country":"Finland","latitude":60.1680,"longitude":24.9320}', '{"musicalGenres":["ambient","experimental"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":25}', NOW(), NOW()),
('user-025', 'minna@polydom.io', '$2a$10$PLACEHOLDER_HASH', 'Minna', 'Laine', '+358403000017', 'USER', '{"city":"Kuopio","country":"Finland","latitude":62.8924,"longitude":27.6770}', '{"musicalGenres":["jazz","world music"],"notificationSettings":{"email":true,"sms":false,"push":true,"marketingEmails":false},"searchRadius":60}', NOW(), NOW())
ON CONFLICT (email) DO UPDATE SET
  first_name = EXCLUDED.first_name,
  last_name = EXCLUDED.last_name,
  role = EXCLUDED.role,
  updated_at = NOW();
