-- Custom migration: sample seed data

-- 0001_sample_data: Seed bookings, payments, and booking activities
-- Generated by scripts/sample-data/generate-sql-migrations.ts

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-001', 'user-001', 'event-001', 'vendor-001', 2, 50, 'EUR',
  'ATTENDED', 'GENERAL', NULL, NULL, 'web', '{"notes":"Jazz night booking"}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-002', 'user-002', 'event-002', 'vendor-001', 1, 40, 'EUR',
  'CONFIRMED', 'STUDENT', NULL, NULL, 'mobile', '{"notes":"Workshop booking"}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-003', 'user-003', 'event-003', 'vendor-002', 3, 96, 'EUR',
  'CONFIRMED', 'GENERAL', NULL, NULL, 'web', '{}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-004', 'user-004', 'event-004', 'vendor-002', 2, 70, 'EUR',
  'ATTENDED', 'GENERAL', 'EARLY10', 7, 'web', '{}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-005', 'user-005', 'event-005', 'vendor-003', 4, 200, 'EUR',
  'CONFIRMED', 'VIP', NULL, NULL, 'mobile', '{}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-006', 'user-006', 'event-006', 'vendor-003', 1, 0, 'EUR',
  'ATTENDED', 'FREE', NULL, NULL, 'web', '{}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-007', 'user-007', 'event-007', 'vendor-004', 2, 60, 'EUR',
  'CANCELLED', 'GENERAL', NULL, NULL, 'web', '{"cancelReason":"Schedule conflict"}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-008', 'user-008', 'event-008', 'vendor-004', 1, 35, 'EUR',
  'ATTENDED', 'GENERAL', NULL, NULL, 'app', '{}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-009', 'user-009', 'event-009', 'vendor-005', 3, 75, 'EUR',
  'CONFIRMED', 'GENERAL', NULL, NULL, 'web', '{}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-010', 'user-010', 'event-010', 'vendor-005', 2, 90, 'EUR',
  'ATTENDED', 'VIP', 'VIP20', 18, 'app', '{}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-011', 'user-011', 'event-011', 'vendor-006', 1, 25, 'EUR',
  'CONFIRMED', 'GENERAL', NULL, NULL, 'web', '{}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-012', 'user-012', 'event-012', 'vendor-006', 1, 30, 'EUR',
  'NO_SHOW', 'GENERAL', NULL, NULL, 'web', '{}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-013', 'user-013', 'event-013', 'vendor-007', 2, 50, 'EUR',
  'ATTENDED', 'GENERAL', NULL, NULL, 'mobile', '{}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-014', 'user-014', 'event-014', 'vendor-007', 1, 25, 'EUR',
  'REFUNDED', 'GENERAL', NULL, NULL, 'web', '{"refundReason":"Event cancelled"}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-015', 'user-015', 'event-015', 'vendor-008', 3, 135, 'EUR',
  'CONFIRMED', 'VIP', NULL, NULL, 'app', '{}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-016', 'user-001', 'event-016', 'vendor-001', 2, 60, 'EUR',
  'ATTENDED', 'GENERAL', NULL, NULL, 'web', '{}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-017', 'user-002', 'event-017', 'vendor-001', 1, 25, 'EUR',
  'CONFIRMED', 'GENERAL', NULL, NULL, 'app', '{}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-018', 'user-003', 'event-018', 'vendor-002', 2, 80, 'EUR',
  'ATTENDED', 'GENERAL', NULL, NULL, 'web', '{}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-019', 'user-016', 'event-019', 'vendor-008', 1, 20, 'EUR',
  'CONFIRMED', 'GENERAL', NULL, NULL, 'mobile', '{}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO bookings (id, user_id, event_id, vendor_id, ticket_count, total_amount, currency, status, ticket_type, promo_code, discount_amount, source, metadata, created_at, updated_at)
VALUES (
  'booking-020', 'user-017', 'event-020', 'vendor-003', 2, 50, 'EUR',
  'ATTENDED', 'GENERAL', NULL, NULL, 'web', '{}', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-001', 'booking-001', 50, 'EUR', 'COMPLETED', 'STRIPE',
  'pi_test_001', NULL, NULL, '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-002', 'booking-002', 40, 'EUR', 'COMPLETED', 'STRIPE',
  'pi_test_002', NULL, NULL, '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-003', 'booking-003', 96, 'EUR', 'COMPLETED', 'STRIPE',
  'pi_test_003', NULL, NULL, '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-004', 'booking-004', 70, 'EUR', 'COMPLETED', 'CREDIT_CARD',
  'pi_test_004', NULL, NULL, '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-005', 'booking-005', 200, 'EUR', 'COMPLETED', 'STRIPE',
  'pi_test_005', NULL, NULL, '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-006', 'booking-006', 0, 'EUR', 'COMPLETED', 'STRIPE',
  'pi_test_006', NULL, NULL, '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-007', 'booking-007', 60, 'EUR', 'REFUNDED', 'STRIPE',
  'pi_test_007', 60, 'Customer cancellation', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-008', 'booking-008', 35, 'EUR', 'COMPLETED', 'APPLE_PAY',
  'pi_test_008', NULL, NULL, '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-009', 'booking-009', 75, 'EUR', 'COMPLETED', 'STRIPE',
  'pi_test_009', NULL, NULL, '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-010', 'booking-010', 90, 'EUR', 'COMPLETED', 'STRIPE',
  'pi_test_010', NULL, NULL, '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-011', 'booking-011', 25, 'EUR', 'COMPLETED', 'GOOGLE_PAY',
  'pi_test_011', NULL, NULL, '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-012', 'booking-012', 30, 'EUR', 'COMPLETED', 'STRIPE',
  'pi_test_012', NULL, NULL, '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-013', 'booking-013', 50, 'EUR', 'COMPLETED', 'STRIPE',
  'pi_test_013', NULL, NULL, '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-014', 'booking-014', 25, 'EUR', 'REFUNDED', 'STRIPE',
  'pi_test_014', 25, 'Event cancelled by vendor', '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-015', 'booking-015', 135, 'EUR', 'COMPLETED', 'STRIPE',
  'pi_test_015', NULL, NULL, '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-016', 'booking-016', 60, 'EUR', 'COMPLETED', 'PAYPAL',
  'pi_test_016', NULL, NULL, '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-017', 'booking-017', 25, 'EUR', 'PENDING', 'STRIPE',
  'pi_test_017', NULL, NULL, '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-018', 'booking-018', 80, 'EUR', 'COMPLETED', 'STRIPE',
  'pi_test_018', NULL, NULL, '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-019', 'booking-019', 20, 'EUR', 'COMPLETED', 'DEBIT_CARD',
  'pi_test_019', NULL, NULL, '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO payments (id, booking_id, amount, currency, status, method, stripe_payment_intent_id, refund_amount, refund_reason, created_at, updated_at)
VALUES (
  'pay-020', 'booking-020', 50, 'EUR', 'COMPLETED', 'STRIPE',
  'pi_test_020', NULL, NULL, '2026-05-01T00:00:00Z', NOW()
);

INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-001', 'user-001', 'BOOKING_CREATED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-001', 'user-001', 'BOOKING_CONFIRMED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-001', 'user-001', 'BOOKING_CANCELLED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-001', 'user-001', 'BOOKING_ATTENDED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-002', 'user-002', 'BOOKING_CREATED', '{"bookingStatus":"CONFIRMED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-002', 'user-002', 'BOOKING_CONFIRMED', '{"bookingStatus":"CONFIRMED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-003', 'user-003', 'BOOKING_CREATED', '{"bookingStatus":"CONFIRMED","ticketCount":3}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-003', 'user-003', 'BOOKING_CONFIRMED', '{"bookingStatus":"CONFIRMED","ticketCount":3}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-004', 'user-004', 'BOOKING_CREATED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-004', 'user-004', 'BOOKING_CONFIRMED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-004', 'user-004', 'BOOKING_CANCELLED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-004', 'user-004', 'BOOKING_ATTENDED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-005', 'user-005', 'BOOKING_CREATED', '{"bookingStatus":"CONFIRMED","ticketCount":4}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-005', 'user-005', 'BOOKING_CONFIRMED', '{"bookingStatus":"CONFIRMED","ticketCount":4}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-006', 'user-006', 'BOOKING_CREATED', '{"bookingStatus":"ATTENDED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-006', 'user-006', 'BOOKING_CONFIRMED', '{"bookingStatus":"ATTENDED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-006', 'user-006', 'BOOKING_CANCELLED', '{"bookingStatus":"ATTENDED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-006', 'user-006', 'BOOKING_ATTENDED', '{"bookingStatus":"ATTENDED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-007', 'user-007', 'BOOKING_CREATED', '{"bookingStatus":"CANCELLED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-007', 'user-007', 'BOOKING_CONFIRMED', '{"bookingStatus":"CANCELLED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-007', 'user-007', 'BOOKING_CANCELLED', '{"bookingStatus":"CANCELLED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-008', 'user-008', 'BOOKING_CREATED', '{"bookingStatus":"ATTENDED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-008', 'user-008', 'BOOKING_CONFIRMED', '{"bookingStatus":"ATTENDED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-008', 'user-008', 'BOOKING_CANCELLED', '{"bookingStatus":"ATTENDED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-008', 'user-008', 'BOOKING_ATTENDED', '{"bookingStatus":"ATTENDED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-009', 'user-009', 'BOOKING_CREATED', '{"bookingStatus":"CONFIRMED","ticketCount":3}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-009', 'user-009', 'BOOKING_CONFIRMED', '{"bookingStatus":"CONFIRMED","ticketCount":3}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-010', 'user-010', 'BOOKING_CREATED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-010', 'user-010', 'BOOKING_CONFIRMED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-010', 'user-010', 'BOOKING_CANCELLED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-010', 'user-010', 'BOOKING_ATTENDED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-011', 'user-011', 'BOOKING_CREATED', '{"bookingStatus":"CONFIRMED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-011', 'user-011', 'BOOKING_CONFIRMED', '{"bookingStatus":"CONFIRMED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-012', 'user-012', 'BOOKING_CREATED', '{"bookingStatus":"NO_SHOW","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-012', 'user-012', 'BOOKING_CONFIRMED', '{"bookingStatus":"NO_SHOW","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-013', 'user-013', 'BOOKING_CREATED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-013', 'user-013', 'BOOKING_CONFIRMED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-013', 'user-013', 'BOOKING_CANCELLED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-013', 'user-013', 'BOOKING_ATTENDED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-014', 'user-014', 'BOOKING_CREATED', '{"bookingStatus":"REFUNDED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-014', 'user-014', 'BOOKING_CONFIRMED', '{"bookingStatus":"REFUNDED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-014', 'user-014', 'BOOKING_CANCELLED', '{"bookingStatus":"REFUNDED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-014', 'user-014', 'BOOKING_ATTENDED', '{"bookingStatus":"REFUNDED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-015', 'user-015', 'BOOKING_CREATED', '{"bookingStatus":"CONFIRMED","ticketCount":3}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-015', 'user-015', 'BOOKING_CONFIRMED', '{"bookingStatus":"CONFIRMED","ticketCount":3}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-016', 'user-001', 'BOOKING_CREATED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-016', 'user-001', 'BOOKING_CONFIRMED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-016', 'user-001', 'BOOKING_CANCELLED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-016', 'user-001', 'BOOKING_ATTENDED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-017', 'user-002', 'BOOKING_CREATED', '{"bookingStatus":"CONFIRMED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-017', 'user-002', 'BOOKING_CONFIRMED', '{"bookingStatus":"CONFIRMED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-018', 'user-003', 'BOOKING_CREATED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-018', 'user-003', 'BOOKING_CONFIRMED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-018', 'user-003', 'BOOKING_CANCELLED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-018', 'user-003', 'BOOKING_ATTENDED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-019', 'user-016', 'BOOKING_CREATED', '{"bookingStatus":"CONFIRMED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-019', 'user-016', 'BOOKING_CONFIRMED', '{"bookingStatus":"CONFIRMED","ticketCount":1}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-020', 'user-017', 'BOOKING_CREATED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-020', 'user-017', 'BOOKING_CONFIRMED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-020', 'user-017', 'BOOKING_CANCELLED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');
INSERT INTO booking_activities (booking_id, user_id, event_type, metadata, timestamp)
VALUES ('booking-020', 'user-017', 'BOOKING_ATTENDED', '{"bookingStatus":"ATTENDED","ticketCount":2}', '2026-05-01T00:00:00Z');